<?php
/** @file
 *
 *  HTML rendering of the an "Item Cloud" as a list of items.
 *
 *  Incoming parameters:
 *      itemList        The Connexions_Model_Set_Adapter_ItemList instance
 *                      representing the items to present;
 *      weightName      The name of the weight field
 *                      (null == don't include weight);
 *      weightTitle     The title describing the weight field;
 *      titleName       The name of the title field;
 *      titleTitle      The title describing the title field;
 *      itemType        The type of item
 *                      (View_Helper_HtmlItemCloud::ITEM_TYPE_USER |
 *                                                  ITEM_TYPE_ITEM);
 *
 */
$itemList      =& $this->itemList;

$includeWeight =  ($this->weightName !== null);
$titleTitle    =  ($this->titleTitle !== null
                    ? $this->titleTitle
                    : ($this->itemType ===
                            View_Helper_HtmlItemCloud::ITEM_TYPE_USER
                        ? 'User'
                        : 'Item'
                    )
                  );
$weightTitle   =  ($this->weightTitle !== null
                    ? $this->weightTitle
                    : 'Weight');

?>
<ul class='Item_List'>
 <li class='header'><span class='item'><?= $titleTitle ?></span><?php

if ($includeWeight)
{
    ?><span class='itemCount'><?= $weightTitle ?></span><?php
}

?></li><?php

$idex = 0;
foreach ($itemList as $item)
{
    $oddEven = ($idex % 2 ? 'odd' : 'even');
    $url     = $item->getParam('url');
    $weight  = number_format(round($item->getWeight()));
    $title   = $item->getTitle();

    ?><li class='<?= $oddEven ?>'><?php

    if (empty($url))
    {
        ?><span class='item'><?= $title ?></span><?php

    }
    else
    {
        ?><a class='item' 
              href='<?= htmlSpecialChars($url) ?>'><?= $title ?></a><?php
    }

    if ($includeWeight)
    {
        $elTitle = ($this->weightTitle !== null
                        ? " title='". htmlspecialchars($this->wieghtTitle) ."'"
                        : '');

        ?><span class='itemCount'<?= $elTitle ?>><?= $weight ?></span><?php
    }

    ?></li><?php
}

?>
</ul>
