<?php
/** @file
 *
 *  Render this user item page with pagination controls.
 *
 *  $this implements the Zend_View_Interface and has at least the following
 *  members/methods:
 *      pageCount
 *      itemCountPerPage
 *      first
 *      current
 *      last
 *      next
 *      pagesInRange [ 1:1, 2:2, 3:3 ]
 *      firstPageInRange
 *      lastPageInRange
 *      currentItemCount
 *      totalItemCount
 *      firstItemNumber
 *      lastItemNumber
 *
 *      excludeInfo   - true to exclude paging information
 *      cssClass      - css class for the form
 */

$marker         = array('first' => '&laquo;',   //'&#x00ab',    //'&laquo;',
                        'prev' => '&lsaquo;',  //'&#x2039',    //'&lsaquo;',
                        'next' => '&rsaquo;',  //'&#x203a',    //'&rsaquo;',
                        'last' => '&raquo;'    //'&#x00bb',    //'&raquo;',
                );
$cssClass       = 'ui-corner-all';
$perPageChoices = array(10, 25, 50, 100, 250, 500);

/*
Connexions::log('paginationControl.phtml: vars[ '.
                    print_r(get_object_vars($this), true) .' ]');
// */


printf (  "<form class='pagination%s'>" // { pagination
        .  "<div class='pager'>",       // { pager
        (@isset($this->cssClass)
          ? " ". $this->cssClass
          : ""));


if ($this->pageCount > 1)
{
    // Present the pages BEFORE the current range
    if ($this->firstPageInRange > $this->first)
    {
        printf (  "<button type='submit' name='page' "
                .                      "class='ends-left ui-state-default %s' "
                .                      "value='%s' "
                .                      "title='Previous Page'>%s</button>"
                . "<button type='submit' name='page' "
                .                      "class='ui-state-default %s' "
                .                      "value='%s'>%s</button>",
                $cssClass, $this->previous, $marker['prev'],
                $cssClass, $this->first,    $this->first);
    
        if ($this->firstPageInRange > ($this->first + 1))
            printf (  "<button type='submit' name='page' "
                    .                      "class='ui-state-default %s' "
                    .                      "value='%s'>%s</button>",
                    $cssClass, $this->first + 1, $this->first + 1,
                                                 $this->first + 1);
    
        if ($this->firstPageInRange > ($this->first + 2))
            printf("<span class='ui-state-skip %s'>...</span>",
                   $cssClass);
    }
    else
    {
        printf (  "<button type='submit' name='page' "
                .                      "class='ends-left ui-state-%s %s' "
                .                      "%s"
                .                      "value='%s' "
                .                      "title='Previous Page'>%s</button>",
                (@isset($this->previous)
                    ? 'default'
                    : 'disabled'),
                $cssClass,
                (@isset($this->previous)
                    ? ''
                    : 'disabled '),
                (@isset($this->previous)
                    ? $this->previous
                    : ''),
                $marker['prev']);
        /*
        if (@isset($this->previous))
            printf (  "<button type='submit' name='page' "
                    .                      "class='ends-left "
                    .                             "ui-state-default %s' "
                    .                      "value='%s' "
                    .                      "title='Previous Page'>%s</button>",
                    $cssClass, $this->previous, $marker['prev']);
        else
            printf ("<span class='ends-left ui-state-disabled %s' "
                    .               "title='Previous Page'>%s</span>",
                    $cssClass, $marker['prev']);
        */
    }
    
    // Present the pages within the current range
    foreach ($this->pagesInRange as $page)
    {
        if ($page == $this->current)
            printf ("<button class='ui-state-active %s'>%s</button>",
                    $cssClass, ($page));
        else
            printf (  "<button type='submit' name='page' "
                    .                      "class='ui-state-default %s' "
                    .                      "value='%s'>%s</button>",
                    $cssClass, $page, $page, $page);
                    //$this->url(array('page' => $page)), $page);
    }
    
    
    // Present the pages AFTER the current range
    if ($this->lastPageInRange < $this->last)
    {
        if ($this->lastPageInRange < ($this->last - 2))
            printf ("<span class='ui-state-skip %s'>...</span>",
                    $cssClass);
    
        if ($this->lastPageInRange < ($this->last - 1))
            printf (  "<button type='submit' name='page' "
                    .                      "class='ui-state-default %s' "
                    .                      "value='%s'>%s</button>",
                    $cssClass, $this->last - 1, $this->last - 1,
                                                $this->last - 1);
    
        printf (  "<button type='submit' name='page' "
                .                      "class='ui-state-default %s' "
                .                      "value='%s'>%s</button>"
                . "<button type='submit' name='page' "
                .                      "class='ends-right ui-state-default %s' "
                .                      "value='%s' "
                .                      "title='Next Page'>%s</button>",
                $cssClass, $this->last, $this->last,
                $cssClass, $this->next, $marker['next']);
    }
    else
    {
        printf (  "<button type='submit' name='page' "
                .                      "class='ends-right ui-state-%s %s' "
                .                      "%s"
                .                      "value='%s' "
                .                      "title='Next Page'>%s</button>",
                (@isset($this->next)
                    ? 'default'
                    : 'disabled'),
                $cssClass,
                (@isset($this->next)
                    ? ''
                    : 'disabled '),
                (@isset($this->next)
                    ? $this->next
                    : ''),
                $marker['next']);
    
        /*
        if (@isset($this->next))
            printf (  "<button type='submit' name='page' "
                    .                      "class='ends-right "
                    .                             "ui-state-default %s' "
                    .                      "value='%s' "
                    .                      "title='Next Page'>%s</button>",
                    $cssClass, $this->next, $marker['next']);
        else
            printf ("<span class='ends-right ui-state-disabled %s' "
                    .                   "title='Next Page'>%s</span>",
                    $cssClass, $marker['next']);
        */
    }
}
else
{
    echo "&nbsp;";
}

echo  "</div>";                     // pager }

if ( (! @isset($this->excludeInfo)) || (! $this->excludeInfo) )
{
    echo    "<div class='info'>";   // { info

    /*
    printf (      "<div class='itemCount'>"
            .       "<span class='label'>Items:</span>"
            .       "<span class='count %s'>%s</span>"
            .     "</div>",
            $cssClass, number_format($this->totalItemCount));
     */
    $totalItemCount   = $this->totalItemCount;
    $pageCount        = $this->pageCount;
    $itemCountPerPage = $this->itemCountPerPage;
    
    printf (  "<div class='perPage'>"
            .   "<div class='itemCount'>%s</div>"
            .   "item%s"
            /*
            .   " in"
            .   "<div class='pageCount'>%s</div>"
            .   "page%s"
            */
            .   " with"
            .   "<select class='ui-input ui-state-default "
            .                  "count %s' name='perPage'>",
            number_format($totalItemCount),
            ($totalItemCount === 1 ? "" : "s"),
            //number_format($pageCount),
            //($pageCount      === 1 ? "" : "s"),
            $cssClass);
    
    foreach ($perPageChoices as $perPage)
    {
        printf ( "<option value='%s'%s>%s</option>",
                     $perPage,
                     ($perPage == $itemCountPerPage
                        ? ' selected'
                        : ''),
                     $perPage);
    }
    
    printf (    "</select>"
            .   "item%s per page."
            . "</div>"
            . "<div class='itemRange'>"
            .   "Current viewing"
            /*
            .   "page %s,"
            */
            .   " items"
            .   "<div class='count %s'>%s - %s</div>."
            . "</div>"
            ."</div>",      // info }
            ($itemCountPerPage === 1 ? "" : "s"),
            //number_format($this->current),
            $cssClass, number_format($this->firstItemNumber),
                       number_format($this->lastItemNumber));
}

echo "</form>";                     // pagination }
