<?php
/** @file
 *
 *  Given a Model_UserItemSet instance 'userItems', render a tag cloud for all
 *  tags of the userItems.
 *
 *  $this implements the Zend_View_Interface and has at least the following
 *  members/methods:
 *      tagSet      A Model_TagSet instance representing the tags to be
 *                  presented.  Note that this set MAY NOT match the list of
 *                  tags in tagInfo->validTags NOR directly correlate to
 *                  tagInfo->reqTags
 *                  (e.g. when the tag cloud representes all the tags for a set
 *                        of userItems);
 *      tagInfo     A Connexions_TagInfo instance containing information about
 *                  the requested tags.
 *      maxTags     The maximum number of tags to present
 *                  [100 via $tagSet->get_Tag_ItemList()];
 *      sortBy      The tag field to sort by ['tag'];
 *      sortOrder   Sort order ( ['ASC'] | 'DESC').
 *
 *
 *  Note: Within a view, use EITHER this partial:
 *          $view->partial('tagCloud.phtml',
 *                         array('tagSet'   => &$tagSet,
 *                               'tagInfo'  => &$tagInfo));
 *
 *        OR the Connexions_View_Helper_HtmlTagCloud:
 *          $view->htmlTagCloud();
 *
 *        Both make use of the Connexions_View_Helper_HtmlTagItem helper
 *        to render individual tag items.
 */
if ( (! @isset($this->tagSet)) || (! $this->tagSet instanceof Model_TagSet) )
    return;

if (! @isset($this->maxTags))       $this->maxTags   = null;
if (! @is_string($this->sortBy))    $this->sortBy    = 'tag';
if (! @is_string($this->sortOrder)) $this->sortOrder = 'ASC';

// /*
Connexions::log(sprintf("tagCloud.phtml:: tagInfo[ %s ], maxTags[ %d ], ".
                            "sortBy[ %s ], sortOrder[ %s ]<br />\n",
                        print_r($this->tagInfo, true),
                        $this->maxTags, $this->sortBy, $this->sortOrder));
// */

// Grab the Zend_Tag_ItemList adapter for our tag set.
$tagItemList = $this->tagSet->get_Tag_ItemList($this->maxTags,
                                               $this->tagInfo);

// Create a sort function
$refA    = '$a["'. $this->sortBy .'"]';
$refB    = '$b["'. $this->sortBy .'"]';
$funcDef = '$cmp = '
         .       (strpos($this->sortBy, 'Count')
                        ? // Numeric comparison
                          $refA .'-'. $refB
                        : // String comparison
                          'strcasecmp('. $refA .','. $refB .')') .';'
         .  ( (($this->sortOrder === 'ASC') || ($this->sortOrder === 'asc'))
                    ? ''
                      // Reverse the comparison to reverse the ASC sort
                    : '$cmp = ($cmp < 0 '
                      .         '? 1 '
                      .         ': ($cmp > 0 '
                      .             '? -1 '
                      .             ': 0));')
       //. 'echo "a[",'. $refA .',"],b[", '. $refB .',"]: cmp[",$cmp,"]\n";'
         . 'return  $cmp;';
//printf ("funcDef[ %s ]<br />\n", $funcDef);
$sortFn  = create_function('$a,$b', $funcDef);


// Sort the tagItemList
$tagItemList->uasort($sortFn);

/*
$loader = $this->getPluginLoader('helper');
$loader->addPrefixPath('Zend_Tag_Cloud_Decorator_',
                        APPLICATION_PATH .'/../librry/Zend/Tag/Cloud/Decorator/');
*/

// Create a Zend_Tag_Cloud renderer and render the tag cloud
$cloud = new Zend_Tag_Cloud(
                array(
                    /* Make the Connexions_View_Helper_HtmlTagItem helper
                     * available.
                     */
                    'prefixPath'            => array(
                        'prefix'    => 'Connexions_View_Helper',
                        'path'      => APPLICATION_PATH .'/views/helpers/'
                     ),
                    'ItemList'              => $tagItemList,
                    'CloudDecorator'        => array(
                        'decorator'         => 'htmlCloud',
                        'options'           => array(
                            'HtmlTags'      => array(
                                'ul'        => array(
                                    'class' =>'Tag_Cloud clearfix'
                                )
                            )
                        )
                    ),
                    'TagDecorator'          => array(
                        /* Use the Connexions_View_Helper_HtmlTagItem helper
                         * to render tag items.
                         */
                        'decorator'         => 'htmlTagItem',   //'htmlTag',
                        'options'           => array(
                            'HtmlTags'      => array(
                                'li'        => array(
                                    'class'=>'tag'
                                )
                            ),
                            'ClassList'     => array(
                                'size0', 'size1', 'size2', 'size3',
                                'size4', 'size5', 'size6'
                            )
                        )
                    )
                ));

echo $cloud->render();
