<?php
/** @file
 *
 *  Render a single userItem.
 *
 *  $this implements the Zend_View_Interface and has at least the following
 *  members/methods:
 *      userItem        The Model_UserItem instance to present.
 */
if ((! @isset($this->userItem)) ||
    (! $this->userItem instanceof Model_UserItem))
{
    return;
}

printf ("<li class='item'>Item %s: %s </li>\n",
        (@isset($this->index) ? $this->index : ''),
        $this->userItem->debugDump());
