<?php
/** @file
 *
 *  Render a single user within a user list.
 *
 *  $this implements the Zend_View_Interface and has at least the following
 *  members/methods:
 *      user    The Model_User instance to present.
 *      index   The (optional) index within the list.
 */
if ((! @isset($this->user)) ||
    (! $this->user instanceof Model_User))
{
    return;
}

printf ("<li class='item'>User %s: %s </li>\n",
        (@isset($this->index) ? $this->index : ''),
        $this->user->debugDump());

