<?php
/** @file
 *
 *  Generic user view script.
 *
 *  Incoming members:
 *      user            The Model_User instance to render.
 *      viewer          The Model_User instance to render.
 *      showParts       An array indicating which portions of the user record
 *                      to present;
 *      maxTags         The maximum number of tags to present for a user [ 5 ];
 *      sortBy          The current sorting order if this user entry is being
 *                      rendered in a list;
 *      tags            A Model_Set_Tag instance of tags that should be
 *                      highlighted;
 */
$user          =& $this->user;
$viewer        =  $this->viewer;    // MAY be unset, hence the missing '=&'
$showParts     =& $this->showParts;
$maxTags       =  ( isset($this->maxTags)
                        ? $this->maxTags
                        : 5 );
$highlightTags = ($this->tags && ($this->tags instanceof Model_Set_Tag)
                        ? $this->tags->__toString()
                        : null);

$isMe          = ( $viewer && $viewer->isSame($user) );
//$relation      = $user->networkRelation( $viewer );
$userUrl       = $this->url(array('controller' => 'index',
                                'action'     => 'index',
                                'owner'      => $user->name));

$links         = $this->headLink();
$links->appendStylesheet($this->baseUrl('/css/users.css'));

$css = array();
array_push($css, ($isMe ? 'me' : 'other'));

if ($showParts['minimized'])    array_push($css, 'minimized');

?>
 <li class='item person <?= implode(' ', $css) ?>'>
  <form class='user'>
   <input type='hidden' name='userId' value='<?= $user->userId ?>' /><?php

    /*****************************
     * Stats
     *
     */
    if ($showParts['user:stats'] === true)
    {
        ?>
   <div class='stats ui-corner-bottom'><?php

        if ($showParts['user:stats:countItems'] === true)
        {
            $count = number_format($user->totalItems);

            echo "<a class='countItems' ",
                     "href='{$userUrl}' ",
                    "title='Bookmarks'>",
                   $count,
                 "</a>";
        }

        if ($showParts['user:stats:countTags'] === true)
        {
            $count = number_format($user->totalTags);
            $url   = $this->url(array('controller' => 'tags',
                                      'action'     => 'index',
                                      'owner'      => $user->name));

            // Watch the white-space...
            echo "<a class='countTags' ",
                     "href='{$url}' ",
                    "title='Tags'>",
                  "<div class='icon icon-active'>",
                   "<div class='ui-icon ui-icon-tag'>",
                    "&nbsp;",
                   "</div>",
                  "</div>",
                  $count,
                 "</a>";
        }

        ?>
   </div><?php
    }

    /*****************************
     * User Data
     *
     */
    ?>
   <div class='data'><?php  // data {

    $clearFloats = $showParts['minimized'];


    /*****************************
     * Avatar
     *
     */
    if ($showParts['user:data:avatar'] === true)
    {
        echo "<div class='avatar'>",
              "<a href='{$userUrl}' title='{$user->fullName}'>",
               "<div class='img icon-highlight'>";

        if (! empty($user->pictureUrl))
        {
            echo "<img src='", $user->pictureUrl, "' />";
        }
        else
        {
            echo "<div class='ui-icon ui-icon-person'>&nbsp;</div>";
        }

        echo   "</div>",
              "</a>",
             "</div>";
    }

    /*****************************
     * UserId
     *
     */
    if ($showParts['user:data:userId'] === true)
    {
        echo "<div class='userId' title='User id'>",
              "<a href='{$userUrl}' title='User Id'>",
               "<span class='name'>{$user->name}</span>",
              "</a>",
             "</div>";
    }

    /*****************************
     * fullName
     *
     */
    if ($showParts['user:data:fullName'] === true)
    {
        echo "<div class='fullName' ",
                  "title='Full Name'>";

        if ($showParts['user:data:userId'] !== true)
        {
            echo "<a href='{$userUrl}' ",
                   "title='Full Name'>",
                  $this->escape($user->fullName),
                 "</a>";
        }
        else
        {
            echo $this->escape($user->fullName);
        }

        echo "</div>";
    }

    /*****************************
     * Email address
     *
     */
    if ($showParts['user:data:email'] === true)
    {
        echo "<div class='email' ",
                  "title='email address'>",
              "<a  href='mailto:{$user->email}' ",
                 "title='email address'>",
               "<div class='icon icon-highlight'>",
                "<div class='ui-icon ui-icon-mail-closed'>",
                 "&nbsp;",
                "</div>",
               "</div>",
               $user->email,
              "</a>",
             "</div>";
    }

    /*****************************
     * Tags
     *
     */
    if (($showParts['user:data:tags'] === true) && ($maxTags > 0))
    {
        echo "<ul class='tags' title='Top {$maxTags} tags'>";

        foreach ($user->getTags('userItemCount DESC', $maxTags) as $tag)
        {
            if ($maxTags-- < 0)
                break;

            $title  = $tag->getTitle();
            $weight = $tag->getWeight();
            $url    = $this->url(array('controller' => 'index',
                                       'action'     => 'index',
                                       'owner'      => $user->name,
                                       'tag'        => $title));

            $cssExtra = ( ($highlightTags !== null) &&
                          (strpos($highlightTags, $tag->tag) !== false)
                            ? ' highlight'
                            : '');

            echo "<li class='tag{$cssExtra}'>",
                  "<a href='{$url}' title='{$title}: {$weight}'>",
                   $title,
                  "</a>",
                 "</li>";

        }

        echo "</ul>";

        $clearFloats = false;
    }

    /*****************************
     * Dates
     *
     */
    if ($showParts['user:data:dates'] === true)
    {
        echo "<div class='dates'>";

        if ($showParts['user:data:dates:lastVisit'] === true)
        {
            echo "<div class='lastVisit' title='Last visited'>",
                  $user->lastVisit,
                 "</div>";
        }

        echo "</div>";

        $clearFloats = false;
    }

    if ($clearFloats)
    {
        ?>
    <br class='clear' /><?php

    }

   ?>
   </div><?php  // data } ?>
  </form>
 </li>
