<?php
/** @file
 *
 *  HTML rendering of the first (highlighed) items.
 *
 *  Incoming parameters:
 *      itemList        The Connexions_Model_Set_Adapter_ItemList instance
 *                      representing the items to present;
 *      highlightCount  The number of items to present;
 *
 */
$itemList       =& $this->itemList;
$highlightCount =  $this->highlightCount;

?>
<div class='highlights ui-corner-all'>
 <h4>Top <?= $highlightCount ?></h4>
 <ul class='Item_List'>
  <?php

    $idex = 0;
    foreach ($itemList as $item)
    {
        if (++$idex > $highlightCount)
            break;

        $oddEven = ($idex % 2 ? 'even' : 'odd');
        $url     = $item->getParam('url');
        $weight  = number_format($item->getWeight());
        $title   = $item->getTitle();

        ?><li class='item <?= $oddEven ?>'><?php

        if (empty($url))
        {
            ?><span class='item'><?= $title ?></span><?php

        }
        else
        {
            ?><a class='item' 
                  href='<?= htmlSpecialChars($url) ?>'><?= $title ?></a><?php
        }

        ?><span class='itemCount'><?= $weight ?></span><?php
        ?></li><?php

    }
  ?>
 </ul>
</div>
