<?php
/** @file
 *
 *  View script for PeopleController::index to render the main content.
 *
 *  The Connexions_View_Helper_HtmlUsers helper MUST be initialized
 *  before this view is rendered.
 *
 *  Incoming members:
 *      viewer              The Model_User instance representing the current
 *                          viewer;
 *      tagInfo             A Connexions_Set_Info instance containing
 *                          information about the requested tags.
 *
 *      paginator           A Zend_Paginator instance established for the
 *                          presentation of the current Model_UserSet;
 */
$baseUrl = $this->baseUrl('/'); //Connexions::url('/');
$links   = $this->headLink();
$links->appendStylesheet($baseUrl .'css/users.css');

$this->headTitle('People');

?>
<div class='columnHeader'>
 <div class='context-bg connexions_sprites user_bg
             ui-corner-left ui-corner-tr'>&nbsp;</div>
 <p>All People<?php
    if ( $this->tagInfo->hasValidItems())
        printf (" with tags '%s'", $this->tagInfo->validItems);
  ?>.
 </p>
</div>

<?= $this->htmlItemScope($this->paginator,
                         $this->tagInfo) ?>

<?= $this->htmlUsers($this->paginator,
                     $this->viewer,
                     $this->tagInfo) ?>

<div class='error'><?= (@isset($this->error) ? $this->error : '') ?></div>
