<?php
/** @file
 *
 *  View script for InboxController::index to render the people portion of the
 *  sidebar.
 *
 *  The Connexions_View_Helper_HtmlItemCloud helper MUST be initialized
 *  before this view is rendered.
 *
 *  Incoming members:
 *      url             The full url for the main controller of this page;
 *      owner           The owner of the current item set -- either a string or
 *                      a Model_User instance;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      tags            A Model_Set_Tag instance containing information about
 *                      any requested tags AND the 'for:%user%' for this inbox;
 *      sidebar         Configuration for the sidebar presentation;
 */
$paneName = 'people';
$config   =  (is_array($this->sidebar['panes']) &&
              is_array($this->sidebar['panes'][$paneName])
                ? $this->sidebar['panes'][$paneName]
                : array());


if ($this->sidebar['initialRender'] === true)
{
    ?>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites user_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>
   <?php
    if (count($this->tags) > 1)
    {
        echo "People related to these bookmarks.";
    }
    else
    {
        printf ("People who tagged one or more items "
                .   "<span class='restrictions'>for '%s'.</span>",
                $this->owner);
    }
    ?>
   </p>
  </div>
    <?php
}

// Tag-related users
$htmlItemCloud = $this->htmlItemCloud($config);
echo $htmlItemCloud->render();
