<?php
/** @file
 *
 *  View script for IndexController::index to render the tags portion of the
 *  sidebar (i.e. the 'Tags' tab).
 *
 *  Incoming members:
 *      url             The full url for the main controller of this page;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      tags            A Model_Set_Tag instance containing information about
 *                      any requested tags (i.e. tag restrictions);
 *      main            An array of settings for the main content panel:
 *      sidebar         An array of settings for the sidebar:
 */

?>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites tag_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>Tags related to these people.</p>
  </div>
  <?php

    $htmlSidebar = $this->htmlSidebar( $this->sidebar );
    $config      = $htmlSidebar->getPane('tags');

    /*
    Connexions::log("index/sidebar-tags.phtml: config[ %s ]",
                    print_r($config, true));
    // */

    $service = Connexions_Service::factory('Model_Tag');

    $perPage    = $config['perPage'];
    $page       = $config['page'];
    if ($perPage < 1)   $perPage = 100;
    if ($page    < 1)   $page    = 1;

    $count      = $perPage;
    $offset     = ($page - 1) * $perPage;

    /* Order by userItem/Bookmark count here so the most used will be in the
     * limited set.  User-requested sorting will be performed later
     * (in View_Helper_HtmlItemCloud) before the cloud is rendered.
     */
    $fetchOrder = array('userCount     DESC',
                        'userItemCount DESC',
                        'tag           ASC');


    if (count($this->tags) < 1)
    {
        /* There were no requested tags that limited the user retrieval so,
         * for the sidebar, retrieve ALL tags...
         */

        /*
        Connexions::log("sidebar-tags.phtml: ALL tags for '%s' [%d..%d]",
                        $this->items, $offset, $offset+$count);
        // */

        $tagSet = $service->fetchByUsers(null,
                                         $fetchOrder,
                                         $count,
                                         $offset);
    }
    else
    {
        // Tags related to the given users
        if ($htmlSidebar->items === null)
        {
            /* There have been no users/items communicated to the
             * htmlSidebar helper (e.g. this is invoked as a partial and
             *                          index.phtml has not been rendered).
             *
             * Use the View_Helper_HtmlUsers view helper to generate the
             * appropriate set now, assuming the controller has filled in
             * $this->main for the configuration of the main view.
             *
             * Tell it NOT to include any script.
             */
            $subOpts = $this->main;
            $subOpts['includeScript'] = false;
            $subOpts['perPage']       = -1;

            $htmlUsers = $this->htmlUsers( $subOpts );
            $items     = $htmlUsers->users;

            /* Tell the sidebar helper about the set of items
             * (I don't thing this really matters).
             */
            $htmlSidebar->items = $items;
        }

        /*
        Connexions::log("sidebar-tags.phtml: bookmarks-related [%d..%d]",
                        $offset, $offset+$count);
        // */
        $tagSet = $service->fetchByUsers( $htmlSidebar->items,
                                          $fetchOrder,
                                          $count,
                                          $offset );
    }

    $config['items']            =& $tagSet;
    $config['selected']         =& $this->tags;
    $config['weightName']       =  'userCount';
    $config['weightTitle']      =  'Users of this tag';
    $config['titleTitle']       =  'Tag';
    $config['itemType']         =  View_Helper_HtmlItemCloud::ITEM_TYPE_ITEM;
    $config['currentSortBy']    =  View_Helper_HtmlItemCloud::SORT_BY_WEIGHT;
    $config['currentSortOrder'] =  Connexions_Service::SORT_DIR_DESC;

    $htmlItemCloud = $this->htmlItemCloud($config);

    echo $htmlItemCloud->render();
