<?php
/** @file
 *
 *  View script for IndexController::index to render the people portion of the
 *  sidebar.
 *
 *  The Connexions_View_Helper_HtmlItemCloud helper MUST be initialized
 *  before this view is rendered.
 *
 *  Incoming members:
 *      url             The full url for the main controller of this page;
 *      owner           The owner of the current item set -- either a string or
 *                      a Model_User instance;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      tags            A Model_Set_Tag instance containing information about
 *                      any requested tags (i.e. tag restrictions);
 *      sidebar         Configuration for the sidebar presentation;
 */
$paneName = 'people';
$config   =  (is_array($this->sidebar['panes']) &&
              is_array($this->sidebar['panes'][$paneName])
                ? $this->sidebar['panes'][$paneName]
                : array());

?>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites user_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>Summary of people<?php

    $nTags = count($this->tags);
    if ($nTags > 0)
    {
        printf ("<span class='restrictions'>using %d tag%s.</span>",
                $nTags,
                ($nTags === 1 ? '' : 's'));
    }
    else
    {
        echo ".";
    }
   
   ?></p>
  </div>
  <?php

    if (isset($config['counts']))
    {
        ?>
  <table class='overview'>
   <tr><th>Total users</th><td><?= $config['counts']['total'] ?></td></tr>
   <tr><th>Contributors
        <div class='threshold'>(<?= $config['counts']['threshold'] ?>
                or more bookmarks)
        </div></th><td><?= $config['counts']['contributors'] ?></td></tr>
  </table>
        <?php
    }

    ?>
  <div id='sb-people-timeline' class='timeline'>
   <div class='timeline-legend'></div>
   <div class='timeline-controls'>
    <input type='hidden' name='timeline.tags' value='<?= $this->tags ?>' />
    <select name='timeline.grouping'>
     <optgroup label="Simple Timelines">
      <option value='YM'  selected>Year, Month</option>
      <option value='YMD'         >Year, Month, Day</option>
      <option value='MD'          >Month, Day</option>
      <option value='MH'          >Month, Hour</option>
      <option value='MDH'         >Month, Day, Hour</option>
     </optgroup>
     <optgroup label="Series Timelines (by Year)">
      <option value='Y:M'         >Month</option>
      <option value='Y:D'         >Day-of-month</option>
      <option value='Y:d'         >Day-of-week</option>
      <option value='Y:H'         >Hour</option>
     </optgroup>
     <optgroup label="Series Timelines (by Month)">
      <option value='M:D'         >Day-of-month</option>
      <option value='M:d'         >Day-of-week</option>
      <option value='M:H'         >Hour</option>
     </optgroup>
     <optgroup label="Series Timelines (by Week)">
      <option value='w:d'         >Day-of-week</option>
      <option value='w:H'         >Hour</option>
     </optgroup>
     <optgroup label="Series Timelines (by Day-of-Month)">
      <option value='D:H'         >Hour</option>
     </optgroup>
     <optgroup label="Series Timelines (by Day-of-Week)">
      <option value='d:H'         >Hour</option>
     </optgroup>
    </select>
   </div>
   <div class='timeline-plot'></div>
  </div>
  <script type='text/javascript'>
(function ($) {
    var $timeline   = $('#sb-people-timeline');

    $timeline.timeline( <?= Zend_Json::encode( $config['timeline'] ) ?> );
 }(jQuery));
  </script>
