<?php
/** @file
 *
 *  View script for IndexController::index to render the main content.
 *
 *  The Connexions_View_Helper_HtmlUserItems helper MUST be initialized
 *  before this view is rendered.
 *
 *  Incoming members:
 *      owner               The owner of the current item set -- either a
 *                          string or a Model_User instance;
 *      viewer              The Model_User instance representing the current
 *                          viewer;
 *      tagInfo             A Connexions_Set_Info instance containing
 *                          information about the requested tags;
 *
 *      paginator           A Zend_Paginator instance established for the
 *                          presentation of the current Model_UserItemSet;
 */
//Connexions_Profile::checkpoint('Connexions', 'IndexView begin');

$baseUrl = $this->baseUrl('/'); //Connexions::url('/');

$links = $this->headLink();
$links->appendStylesheet($baseUrl .'css/userItems.css');

if ($this->owner !== '*')
    $this->headTitle($this->owner ."'s Bookmarks");
else
    $this->headTitle('Bookmarks');

?>
<div class='columnHeader'>
 <div class='context-bg connexions_sprites bookmark_bg
             ui-corner-left ui-corner-tr'>&nbsp;</div>
 <p>Bookmarks of <?= ($this->owner === '*'
                            ? 'all users'
                            : $this->owner) ?>
    <?php
        if (($this->owner instanceof Model_User) &&
            (! empty($this->owner->pictureUrl)) )
        {
            printf ("<img class='avatar' src='%s' title='%s' />\n",
                    $this->owner->pictureUrl,
                    $this->owner->fullName);
        }
    ?>
    <br />
  <?php
    if ( $this->tagInfo->hasValidItems())
        printf ("with tags '%s'.", $this->tagInfo->validItems);
    else
        printf ("NO tags.");
  ?>
 </p>
</div>

<?php
//Connexions_Profile::checkpoint('Connexions', 'IndexView render scope');

echo $this->htmlItemScope($this->paginator,
                          $this->tagInfo);

//Connexions_Profile::checkpoint('Connexions', 'IndexView render items');

echo $this->htmlUserItems($this->paginator,
                          $this->viewer,
                          $this->tagInfo);
?>

<div class='error'><?= (@isset($this->error) ? $this->error : '') ?></div>

<?php

//Connexions_Profile::checkpoint('Connexions', 'IndexView complete');
