<?php
/** @file
 *
 *  View script for IndexController::index to render the people portion of the
 *  sidebar.
 *
 *  The Connexions_View_Helper_HtmlItemCloud helper MUST be initialized
 *  before this view is rendered.
 */

?>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites user_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>People I have tagged items for...</p>
  </div>

