<?php
/** @file
 *
 *  Layout the primary page footer.  This will finish by including
 *  'base-footer.phtml'
 *
 *  Options:
 *      excludeNav      - if true, exclude the navigational components of the
 *                        header, exlude the footer, and ensure that the main
 *                        body has the 'light' class;
 */

$baseUrl = $this->baseUrl();
$config  = Connexions::getConfig();
$app     = $config->app;
$contact = $config->contact;

if ( $this->excludeNav !== true )
{
    ?>
  <div id="pageFooter" class="foot" role="banner">
   <ul class='footer-nav'>
    <li class='icon'
            ><img src='<?= $this->baseUrl('/images/logo.png') ?>'
                  title='connexions' /></li>
    <li class='internal'
            ><a href='<?= $this->baseUrl('/help/about') ?>'>About</a></li>
    <li class='sep'>&middot;</li>
    <li class='internal'
            ><a href='<?= $this->baseUrl('/help') ?>'>Help</a></li>
    <li class='sep'>&middot;</li>
    <li class='internal'
            ><a href='<?= $this->baseUrl('/help/developers') ?>'>API</a></li>
    <li class='sep'>&middot;</li>
    <?php
    if ($contact->services)
    {
        $nServices = count($contact->services);
        $idex      = 0;
        foreach ($contact->services as $type => $service)
        {
            ?>
    <li class='external'
            ><a href='<?= $service->url ?>'><?= ucfirst($type) ?></a></li>
            <?php

            if (++$idex < $nServices)
            {
                ?>
    <li class='sep'>&middot;</li>
                <?php
            }
        }
    }

    ?>
    <li class='info'><?php
      if ($contact->owner || $content->org)
      {
        ?><div class='owner'><?php
        if ($contact->owner)
        {
            if ($contact->owner->label)
            {
                ?><span class='label'><?= $contact->owner->label ?></span><?php
            }

            if ($contact->owner->url)
            {
                $name = ($contact->owner->name
                            ? $contact->owner->name
                            : 'owner');

                ?><a class='name' href='<?= $contact->owner->url ?>'
                    ><?= $name ?></a><?php
            }
            else if ($contact->owner->name)
            {
                ?><span class='name'><?= $contact->owner->name ?></span><?php
            }
        }

        if ($contact->org)
        {
            $img = ($contact->org->img
                        ? "<img src='{$contact->org->img}' />"
                        : "");

            ?><a class='org' href='<?= $contact->org->url ?>'
                ><?= $img ?><?= $contact->org->name ?></a><?php
        }
        ?></div><?php
      }

      if ($app && $app->version && $app->version->major)
      {
        ?><div class='version'>
            <span class='major'><?= $app->version->major ?>.</span
           ><span class='minor'><?= $app->version->minor ?></span>
            <span class='build'>(build <?= $app->version->build ?>)</span>
          </div><?php
      }

    ?>
    </li>
   </ul>

   <?= $this->HtmlDbProfile() ?>
  </div>
<?php
}

?>
 </div><!-- page } -->
<?= $this->render('base-footer.phtml') ?>
