<?php
//$this->headLink()->appendStylesheet(Connexions::url('/css/auth.css'));
//$this->headLink()->appendStylesheet($this->baseUrl('css/auth.css'));
$this->headTitle('Sign In');

$jQuery = $this->jQuery();
$jQuery->addStylesheet($this->baseUrl('css/auth.css'))
       ->addStylesheet($this->baseUrl('css/validationForm.css'))
       /*
       ->addJavascriptFile($this->baseUrl('js/ui.button.min.js'))
       ->addJavascriptFile($this->baseUrl('js/ui.input.min.js'))
       */
       ->addOnLoad('authSignin_onLoad();')
       ->javascriptCaptureStart();
?>
/************************************************
 * UI Initialization
 *
 */
var $form       = null;
var $submit     = null;
var $status     = null;

function authSignin_onLoad()
{
    $form   = $('#auth form');
    $form.hide();   // hide while we prepare....

    $form.addClass('ui-form');

    $status     = $('#auth .status');
    $submit     = $('#auth button[name=method]');

    $submit.button({ priority:'primary', enabled:false});

    // Style all remaining input[type=text] / textarea controls with ui.input
    $('#auth input[type=text],#auth input[type=password],textarea')
            .bind('validation_change', function() {
                    validate_form();
                  })
            .input();

    $form.show();
}

function validate_form()
{
    var $required   = $('.required');
    var isValid     = true;

    $required.each(function() {
        if (! $(this).hasClass('ui-state-valid'))
        {
            isValid = false;
            return false;
        }
    });

    if (isValid)
    {
        $submit.button('enable');
        $status.removeClass('error')
               .addClass('success')
               .text('');
    }
    else
    {
        $submit.button('disable');
        $status.removeClass('success')
               .addClass('error');
    }
}

<?php
$jQuery->javascriptCaptureEnd();

?>
<div class="line"><!-- { -->
 <div id="auth" class='ui-validation-form'>
  <div class='context-ribbon'>&nbsp;</div>
  <div class="legend unit"><!-- { -->
   <h1>Sign in</h1>
   <p>
    or <?= Connexions::anchor('/auth/register', 'Join now') ?>
   </p>
   <div class='status<?= (@isset($this->error) ? ' error' : '') ?>'>
    <?= (@isset($this->error) ? $this->error : '') ?>
   </div>
  </div><!-- legend } -->
  <div class="userInput unit"><!-- { -->
   <form method='post'>
    <div class='field'>
     <label for='username'>User name</label>
     <input type='text' class='text required' name='username'
                        value='<?= $this->username ?>'
                     tabindex='1' />
     <div class='ui-field-info'>
      <div class='ui-field-status'></div>
     </div>
    </div>
    <div class='field'>
     <label for='password' >Password</label>
     <input type='password' class='text required'
            name='password'
                         tabindex='2' />
     <div class='ui-field-info'>
      <div class='ui-field-status'></div>
     </div>
    </div>
    <div class='field buttons'>
     <button name='method' tabindex='3' value='userpassword'>
      Sign-in
     </button>
    </div>
   </form>
 
   <? if ($this->welcome)   echo "Welcome!!<br />"; ?>
  </div><!-- userInput } -->
 </div>
</div><!-- line } -->
