<div id="auth">
    <h1>Sign in</h1>

    <p>You need an account in order to start saving bookmarks.</p>
    <p>Don't have an account? <?= Connexions::anchor('/auth/register/',
                                                     'Create one now!') ?></p>

    <form method='post'>
     <div class='field'>
      <label for='user'>username</label>
      <input type='text' name='user' value='<?= $this->user ?>' />
     </div>
     <div class='field'>
      <label for='password'>password</label>
      <input type='password' name='password' />
     </div>
     <div class='field'>
      <input type='submit' value='Sign in' />
     </div>
    </form>
</div>
