<?php
/** @file
 *
 *  Render the Cloud portion of the Tags Manage section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *
 *      section         The settings section;
 *      cmd             The specific settings command;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'cmds':     [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 *
 *      main            An array of settings for the main body:
 *          namespace       The cookie/parameters/settings namespace for
 *                          the the main body;
 *          viewer          The Model_User instance representing the current
 *                          viewer (typically a reference to $view->viewer);
 *          group           A Model_Set_User instance containing information
 *                          about the Network of 'viewer';
 *
 *
 *          displayStyle    Indicates the current presentation style --
 *                          if this is an array, the style is 'custom';
 *          perPage         The number of results on a single page;
 *          page            The desired page of results;
 *          sortBy          The desired sort field;
 *          sortOrder       The desired sort order;
 *          highlightCount  The number of tags to highlight;
 *
 *          showRelation    Show the relation indicator?;
 *          itemType        The type of item being presented
 *                          (View_Helper_HtmlItemCloud::ITEM_TYPE_*);
 *
 *          paginator       The item paginator;
 *
 *          itemBaseUrl     The baseUrl for item links;
 *
 *          weightName      The name to use for item weights;
 *          weightTitle     The title of item weights;
 *          titleTitle      The title of item names/titles;
 *
 *          currentSortBy   The current sortBy for 'items';
 *          currentSortOrder
 *                          The current sortOrder for 'items';
 *
 */
/*
Connexions::log('views/scripts/settings/main-people-network-list.phtml: '
                . 'main[ %s ]',
                Connexions::varExport($this->main));
// */

$htmlUsers = $this->htmlGroupUsers( $this->main );
echo $htmlUsers->render();
