<?php
/** @file
 *
 *  Render the Account Credentials section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      credentials     The Model_Set_UserAuth instance representing all
 *                      credentials for the current viewer;
 *
 *      section         The settings section;
 *      cmd             The specific settings command;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'cmds':     [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 */

$jQuery = $this->jQuery();
$jQuery->addOnLoad('$.account_credentials_onLoad();')
       ->javascriptCaptureStart();
?>
(function($) {
    var api     = null;
    var $ac     = null;
    var $submit = null;

    function account_credentials_submit($el)
    {
        return;

        $ac.mask();

        // Perform an json-rpc call to save the new information.
        $.jsonRpc(api.jsonRpc, 'user.update', params, {
            success: function(data) {
                if ( (! data) || (data.error !== null))
                {
                    $.notify({
                        title:  'Information Update failed',
                        text:   '<p class="error">'
                              +   (data ? data.error.message : '')
                              + '</p>'
                    });
                }
                else
                {
                    $.notify({
                        title:  'Information Updated',
                        text:   ''
                    });
                }
            },
            error: function(req, textStatus, err) {
                $.notify({
                    title:  'Information Update failed',
                    text:   '<p class="error">'
                          +   textStatus
                          + '</p>'
                });
            },
            complete: function(req, textStatus) {
                $ac.unmask();
                $submit.button('disable');
            }
        });
    }

    $.account_credentials_onLoad = function() {
        api     = $.registry('api');
        $ac     = $('#account-credentials .ui-form');
        $submit = $ac.find('button[name=submit]').button();
        
        $ac.find('input[type=text]').input()
        $ac.bind('change', function(e) {
                    $submit.button('enable');
                })
                .bind('submit', function(e) {
                    e.preventDefault();
                    e.stopPropagation();

                    account_credentials_submit( $(this) );
                });
        $submit.button('disable');
    };

}(jQuery));
<?php
$jQuery->javascriptCaptureEnd();
?>
<ul id='account-credentials' class='credentials'>
 <form class='ui-form'>
  <?php

    // $this->credentials->debugDump();
    foreach ($this->credentials as $auth)
    {
        ?>
  <li class='<?= $auth->authType ?> userInput'>
   <div class='type' title='<?= $auth->authType ?>'><?= $auth->authType ?></div>
   <div class='name'>
    <label  for='name'>Name</label>
    <input type='text'
           name='name'
          class='text'
          value='<?= $auth->name ?>' />
   </div>
   <div class='credential'>
    <label  for='credential'>Credential</label>
    <input type='text'
           name='credential'
          class='text'
          value='<?= $auth->credential ?>' />
    </div>
   <div class='control'>
    <a class='remove' href='#'>remove</a>
   </div>
  </li>
        <?php
    }

 ?>
  <li class='buttons'>
   <div class='control'>
    <a class='add' href='#'>add</a>
   </div>
   <button name='submit'>Save</button>
   <!-- button name='cancel' tabindex='5'>Cancel</button -->
   <br class='clear' />
  </li>
 </form>
</ul>
