<?php
/** @file
 *
 *  Render the Cloud portion of the Tags Manage section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      network         A Model_Set_User instance containing information about
 *                      the Network of 'viewer';
 *
 *      section         The settings section;
 *      cmd             The specific settings command;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'cmds':     [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 *      network         A Model_Set_User instance containing all people in
 *                      the network of 'viewer'.
 *
 *      main            An array of settings for the main body:
 *          namespace       The cookie/parameters/settings namespace for
 *                          the the main body;
 *          viewer          The Model_User instance representing the current
 *                          viewer (typically a reference to $view->viewer);
 *          users           The Model_Set_User instance representing the
 *                          network to be presented;
 *
 *
 *          displayStyle    Indicates the current presentation style --
 *                          if this is an array, the style is 'custom';
 *          perPage         The number of results on a single page;
 *          page            The desired page of results;
 *          sortBy          The desired sort field;
 *          sortOrder       The desired sort order;
 *          highlightCount  The number of tags to highlight;
 *
 *          showRelation    Show the relation indicator?;
 *          itemType        The type of item being presented
 *                          (View_Helper_HtmlItemCloud::ITEM_TYPE_*);
 *
 *          paginator       The item paginator;
 *
 *          itemBaseUrl     The baseUrl for item links;
 *
 *          weightName      The name to use for item weights;
 *          weightTitle     The title of item weights;
 *          titleTitle      The title of item names/titles;
 *
 *          currentSortBy   The current sortBy for 'items';
 *          currentSortOrder
 *                          The current sortOrder for 'items';
 *
 */
Connexions::log('views/scripts/settings/main-people-network-list.phtml: '
                . 'main[ %s ]',
                Connexions::varExport($this->main));

$htmlUsers = $this->htmlUsers( $this->main );
echo $htmlUsers->render();
return;


function alt()
{
$config      = &$this->main;
$namespace   = $config['namespace'];
$panePartial = $config['panePartial'];
$paginator   = $config['paginator'];

$jQuery      = $this->jQuery();
$jsConfig    = array(
                'namespace'         => $namespace,
                'partial'           => $panePartial,
                //'displayOptions'    => $dsConfig,
                'showControls'      => true,
               );
$call        = "$('#{$namespace}Cloud').peopleNetworkPane("
             .               Zend_Json::encode($jsConfig) .");";
$jQuery->addOnLoad($call);

// $this->main->paginator : paginated set of tags
$uiPagination = $this->htmlPaginationControl();
$uiPagination->setNamespace($namespace);

?>
<div    id='<?= $namespace ?>Cloud'
     class='itemItems pane'><!-- pane { -->
 <?= $uiPagination->render($paginator, 'paginator-top') ?>
 <div class='network'><!-- network { -->
  <?php
    if (count($paginator) < 1)  //$paginator->count() 
    {
        echo 'No people currently in your network.';
    }
    else
    {
        ?>
  <ul class='items users'><!-- users { -->
   <?php
        $idex = 0;
        foreach ($paginator as $user)
        {
            $oddEven = (++$idex % 2 ? 'even' : 'odd');
            $name    = $user->name;
            $userUrl = $this->url(array('controller' => 'index',
                                        'action'     => 'index',
                                        'owner'      => $name));
            $tagUrl  = $this->url(array('controller' => 'tags',
                                        'action'     => 'index',
                                        'owner'      => $name));
            $avatar  = (! empty($user->pictureUrl)
                        ? "<img src='{$user->pictureUrl}' />"
                        : "<span class='ui-icon ui-icon-person'>&nbsp;</span>");

            printf ("<!-- user[ %s ] -->", Connexions::varExport($user) );

            ?><li class='<?= $oddEven ?> item user minimized'
                  title='<?= $this->escape($user->fullName) ?>'>
               <form class='user'>
                <div class='stats ui-corner-bottom'>
                 <a class='countItems'
                     href='<?= $userUrl ?>'
                    title='Bookmarks'><?= number_format($user->totalItems)
                                                                        ?></a>
                 <a class='countTags'
                     href='<?= $tagUrl ?>'
                    title='Tags'>
                  <span class='icon icon-active'
                   ><span class='ui-icon ui-icon-tag'>&nbsp;</span
                 ></span><?= number_format($user->totalTags) ?></a>
                </div>
                <div class='data'><!-- data { -->
                 <div class='avatar' title='Avatar'>
                  <a href='<?= $userUrl ?>'>
                   <span class='img icon-highlight'><?= $avatar ?></span>
                  </a>
                 </div>
                 <div class='userId' title='User Id'>
                  <a href='<?= $userUrl ?>'>
                   <span class='name'><?= $name ?></span>
                  </a>
                 </div>
                 <div class='fullName' title='Full Name'>
                  <?= $this->escape($user->fullName) ?>
                 </div>
                 <div class='email' title='Email Address'>
                  <a href='mailto:<?= $user->email ?>'
                   ><span class='icon icon-highlight'
                    ><span class='ui-icon ui-icon-mail-closed'>&nbsp;</span
                     ></span></span
                  ><?= $this->escape($user->email) ?></a>
                 </div>
                 <div class='dates'>
                  <div class='lastVisit' title='Last visited'>
                   <?= $user->lastVisit ?>
                  </div>
                 </div>
                </div><!-- data } -->
               </form>
             </li><?php
        }
   ?>
  </ul><!-- users } -->
<?php
    }
  ?>
 </div><!-- network } -->
 <?= $uiPagination->render($paginator) ?>
 <br class='clear' />
</div><!-- pane } -->
<?php
}
