<?php
/** @file
 *
 *  Render the People Network section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *
 *      section         The settings section;
 *      cmd             The specific settings command;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'cmds':     [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 *
 *      main            An array of settings for the main body:
 *          namespace       The cookie/parameters/settings namespace for
 *                          the the main body;
 *          viewer          The Model_User instance representing the current
 *                          viewer (typically a reference to $view->viewer);
 *          group           A Model_Set_User instance containing information
 *                          about the Network of 'viewer';
 *          panePartial     The partial script to use to render the paginated
 *                          contents of 'group';
 *
 *          displayStyle    Indicates the current presentation style --
 *                          if this is an array, the style is 'custom';
 *          perPage         The number of results on a single page;
 *          page            The desired page of results;
 *          sortBy          The desired sort field;
 *          sortOrder       The desired sort order;
 *          highlightCount  The number of tags to highlight;
 *
 *          showRelation    Show the relation indicator?;
 *          itemType        The type of item being presented
 *                          (View_Helper_HtmlItemCloud::ITEM_TYPE_*);
 */
$config      = &$this->main;
$namespace   = $config['namespace'];
$panePartial = $config['panePartial'];

/*
Connexions::log('views/scripts/settings/main-people-network.phtml: '
                . 'namespace[ %s ], panePartial[ %s ]',
                $namespace, $panePartial);
// */

$jQuery      = $this->jQuery();
$jQuery->addOnLoad('$.people_network_onLoad()')
       ->javascriptCaptureStart();
?>
(function($) {
    $.people_network_onLoad = function() {
        var $section    = $('#people-network');
        var $networkAdd = $section.find('.networkAdd');
        //var $pane       = $section.find('.pane:first');

        $networkAdd.networkAdd();
    };
 }(jQuery));
<?php
$jQuery->javascriptCaptureEnd();


// Top-level, static, non-paginated content
?>
<div id='people-network'><!-- people-network { -->
 <div class='networkAdd ui-form'>
   <div class='field'>
    <label for='networkAdd-input'>Follow User</label>
    <input  id='networkAdd-input' type='text' class='text' />
   </div>
   <button name='submit'>add</button>
 </div>
 <!-- Dynamic, paginated content -->
 <?= $this->partial('settings/'. $panePartial .'.phtml', $this) ?>
</div><!-- people-network } -->
