<?php
/** @file
 *
 *  Render the Tags Manage section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      tags            A Model_Set_Tag instance containing information about
 *                      any tag restrictions / filters;
 *
 *      section         The settings section;
 *      setting         The specific setting;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'settings': [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 *
 *      main            An array of settings for the main body:
 *          namespace       The cookie/parameters/settings namespace for
 *                          the the main body;
 *          viewer          The Model_User instance representing the current
 *                          viewer (typically a reference to $view->viewer);
 *
 *          displayStyle    Indicates the current presentation style --
 *                          if this is an array, the style is 'custom';
 *          perPage         The number of results on a single page;
 *          page            The desired page of results;
 *          sortBy          The desired sort field;
 *          sortOrder       The desired sort order;
 *          highlightCount  The number of tags to highlight;
 *
 *          showRelation    Show the relation indicator?;
 *          itemType        The type of item being presented
 *                          (View_Helper_HtmlItemCloud::ITEM_TYPE_*);
 *
 *          items           The Model_Set_Tag instance representing the
 *                          tag(s) to be presented;
 *          paginator       The item paginator;
 *
 *          itemBaseUrl     The baseUrl for item links;
 *
 *          weightName      The name to use for item weights;
 *          weightTitle     The title of item weights;
 *          titleTitle      The title of item names/titles;
 *
 *          currentSortBy   The current sortBy for 'items';
 *          currentSortOrder
 *                          The current sortOrder for 'items';
 *
 */

$config      = &$this->main;
$namespace   = $config['namespace'];
$panePartial = $config['panePartial'];
$paginator   = $config['paginator'];

Connexions::log('views/scripts/settings/main-tags-manage.phtml: '
                . 'namespace[ %s ], panePartial[ %s ]',
                $namespace, $panePartial);

$jQuery      = $this->jQuery();
$jQuery->addOnLoad('$.tags_manage_onLoad()')
       ->javascriptCaptureStart();
?>
(function($) {
    $.tags_manage_onLoad = function() {
        var $section    = $('#tags-manage');
        var $pane       = $section.find('.pane:first');
        $section.find('.tagFilter').tagsFilter({pane:$pane});
    };
 }(jQuery));
<?php
$jQuery->javascriptCaptureEnd();


// Top-level, static, non-paginated content
?>
<div id='tags-manage'><!-- tags-manage { -->
 <div class='tagFilter ui-form'>
   <div class='field'>
    <label for='tagFilter-input'>Tag Filter</label>
    <input  id='tagFilter-input' type='text' class='text' />
   </div>
   <button name='submit'>filter</button>
   <button name='reset' >clear</button>
 </div>
 <!-- Dynamic, paginated content -->
 <?= $this->partial('settings/'. $this->main['panePartial'] .'.phtml', $this) ?>
</div><!-- tags-manage } -->
