<?php
/** @file
 *
 *  Render the Account ApiKey section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *
 *      section         The settings section;
 *      cmd             The specific settings command;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'cmds':     [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 */

$jQuery = $this->jQuery();
$jQuery->addOnLoad('$.account_apikey_onLoad();')
       ->javascriptCaptureStart();
?>
(function($) {

    $.account_apikey_onLoad = function() {
        $('#account-apiKey').apiKey();
    };

}(jQuery));
<?php
$jQuery->javascriptCaptureEnd();

?>
<div class='line'>
 <form id='account-apiKey'>
  <div class='legend unit'>Current API Key:</div>
  <div class='data lastUnit'>
   <h3 class='apiKey'><?= $this->viewer->apiKey ?></h3>
   <div class='buttons'>
    <button name='submit'>Regenerate</button>
   </div>
  </div>
 </form>
</div>
