<?php
/** @file
 *
 *  Render the Account Credentials section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      credentials     The Model_Set_UserAuth instance representing all
 *                      credentials for the current viewer;
 *
 *      section         The settings section;
 *      cmd             The specific settings command;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'cmds':     [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 */

$jQuery = $this->jQuery();
$jQuery->addOnLoad('$.account_credentials_onLoad();')
       ->javascriptCaptureStart();
?>
(function($) {
    var api         = null;
    var $ac         = null;
    var $buttons    = null;
    var $submit     = null;

    function account_credentials_submit()
    {
        return;

        $ac.mask();

        // Perform an json-rpc call to save the new information.
        $.jsonRpc(api.jsonRpc, 'user.credentialUpdate', params, {
            success: function(data) {
                if ( (! data) || (data.error !== null))
                {
                    $.notify({
                        title:  'Information Update failed',
                        text:   '<p class="error">'
                              +   (data ? data.error.message : '')
                              + '</p>'
                    });
                }
                else
                {
                    $.notify({
                        title:  'Information Updated',
                        text:   ''
                    });
                }
            },
            error: function(req, textStatus, err) {
                $.notify({
                    title:  'Information Update failed',
                    text:   '<p class="error">'
                          +   textStatus
                          + '</p>'
                });
            },
            complete: function(req, textStatus) {
                $ac.unmask();
                $submit.button('disable');
            }
        });
    }

    function account_credentials_delete()
    {
    }

    
    $.account_credentials_onLoad = function() {
        api      = $.registry('api');
        $ac      = $('#account-credentials .ui-validation-form');
        $buttons = $ac.find('.buttons');
        $submit  = $ac.find('button[name=submit]').button();
        $delete  = $ac.find('.delete');
        $add     = $ac.find('.add');
        
        $ac.validationForm()
           .bind('validation_change', function(e) {
                var a   = 1;
            })
           .bind('submit', function(e) {
                e.preventDefault();
                e.stopPropagation();

                if ($ai.validationForm('isValid'))
                {
                    account_credentials_submit();
                }
            });

        $add.click(function(e) {
            var $el = $(this).parent('li');

            e.preventDefault();
            e.stopPropagation();

            var html    = '<li class="new">&nbsp;</li>';
            /*
            var html    = '<li class="new">'
                        +  '<div class="type">
                        +   '<select name="type">'
                        +    '<option class="pki">pki</option>'
                        +    '<option class="openid">openid</option>'
                        +    '<option class="password">password</option>'
                        +   '</select>'
                        +  '</div>'
                        +  '<div class="name">'
                        +   '<label for="name[]">Name</label>'
                        +   '<input type="text" '
                        +          'name="name[]" '
                        +         'class="text" '
                        +         'value="" />'
                        +  '</div>'
                        +  '<div class="credential">'
                        +   '<label for="credential[]">Name</label>'
                        +   '<input type="text" '
                        +          'name="credential[]" '
                        +         'class="text required" '
                        +         'value="" />'
                        +  '</div>'
                        +  '<div class="control">'
                        +   '<a class="delete" href="#">delete</a>'
                        +  '</div>'
                        + '</li>';
             */
            var $div    = $(html);

            $el.before( $div );

            // :XXX: re-bind...
        });

        $delete.click(function(e) {
            var $el = $(this);

            e.preventDefault();
            e.stopPropagation();

            // Present a confirmation dialog and delete.
            var html    = '<div class="confirm">'
                        /*
                        +  '<span class="ui-icon ui-icon-alert" '
                        +        'style="float:left; margin:0 7px 20px 0;">'
                        +  '</span>'
                        */
                        +  'Really delete?<br />'
                        +  '<button name="yes">Yes</button>'
                        +  '<button name="no" >No</button>'
                        + '</div>';
            var $div    = $(html);

            $el.after( $div );
            $el.attr('disabled', true);

            $div.find('button[name=yes]').click(function(e) {
                $el.removeAttr('disabled');
                $div.remove();

                account_credentials_delete();
            });
            $div.find('button[name=no]').click(function() {
                $el.removeAttr('disabled');
                $div.remove();
            });
        });

        /*
        $ac.find('input[type=text]').input()
        $ac.bind('validation_change', function(e) {
                    var $target = $(e.target);
                    if ( $target.input('hasChanged') &&
                         $target.input('isValid') )
                    {
                        $submit.button('enable');
                    }
                    else
                    {
                        $submit.button('disable');
                    }
                })
                .bind('submit', function(e) {
                    e.preventDefault();
                    e.stopPropagation();

                    account_credentials_submit( $(this) );
                });
        $submit.button('disable');
        */
    };

}(jQuery));
<?php
$jQuery->javascriptCaptureEnd();

//$ar   = $this->viewer->getAuthResult();
//$ar->getAuthType());

?>
<ul id='account-credentials' class='credentials'>
 <form class='ui-validation-form'>
  <?php

    // $this->credentials->debugDump();
    foreach ($this->credentials as $auth)
    {
        ?>
  <li class='<?= $auth->authType ?>'>
   <input type='hidden'
          name='userAuthId[]'
         value='<?= $auth->userAuthId ?>' />
   <div class='type'
        title='<?= $auth->authType ?>'><?= $auth->authType ?></div>
   <div class='field name'>
    <label  for='name[]'>Name</label>
    <input type='text'
           name='name[]'
          class='text'
          value='<?= $auth->name ?>' />
   </div>
   <div class='field credential'>
    <label  for='credential[]'>Credential</label>
    <input type='text'
           name='credential[]'
          class='text required'
          value='<?= $auth->credential ?>' />
    </div>
   <div class='field control'>
    <a class='delete' href='#'>delete</a>
   </div>
  </li>
        <?php
    }

 ?>
  <li class='buttons'>
   <div class='control'>
    <a class='add' href='#'>add</a>
   </div>
   <button name='submit'>Save</button>
   <button name='reset'>Reset</button>
   <br class='clear' />
  </li>
 </form>
</ul>
