<?php
/** @file
 *
 *  Render the Account Info section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *
 *      section         The settings section;
 *      cmd             The specific settings command;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'cmds':     [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 */

$avatar = (empty($this->viewer->pictureUrl)
            ? "<div class='connexions_sprites user_bg'>&nbsp;</div>"
            : "<img src='{$this->viewer->pictureUrl}' />" );

$jQuery = $this->jQuery();
$jQuery->addOnLoad('$.account_info_onLoad();')
       ->javascriptCaptureStart();
?>
(function($) {

    $.account_info_onLoad = function() {
        var $info   = $('#account-info');

        $('#account-info').accountInfo();
    };

}(jQuery));
<?php
$jQuery->javascriptCaptureEnd();

?>
<div id='account-info' class='line'><!-- account-info { -->
 <form class='ui-validation-form'><!-- ui-validation-form { -->
  <div class='legend unit'><!-- legend { -->
   <div class='avatar ui-corner-all'>
    <?= $avatar ?>
   </div>
   <div class='user-name' title='User name'>
    <?= $this->viewer->name ?>
   </div>
   <div class='user-date' title='Last visit'>
    <?= substr($this->viewer->lastVisit, 0, 10) ?>
   </div>
  </div><!-- legend } -->
  <div class='userInput lastUnit'><!-- userInput { -->
   <h3 class='user-fullName field' title='Full Name'>
    <label for='fullName'>Full Name</label>
    <input name='fullName' type='text' class='text required' autocomplete='off'
          value='<?= $this->viewer->fullName ?>' tabindex='1' />
    <div class='ui-field-info'>
     <div class='ui-field-status'></div>
     <div class='ui-field-requirements'>required</div>
    </div>
   </h3>
   <div class='user-email field' title='email address'>
    <label  for='email'>email</label>
    <input name='email' type='text' class='text required' autocomplete='off'
          value='<?= $this->viewer->email ?>' tabindex='2' />
    <div class='ui-field-info'>
     <div class='ui-field-status'></div>
     <div class='ui-field-requirements'>required</div>
    </div>
   </div>
   <div class='user-profile field' title='Profile url'>
    <label  for='profile'>Profile url</label>
    <input name='profile' type='text' class='text' autocomplete='off'
          value='<?= $this->viewer->profile ?>' tabindex='3' />
   </div>
   <div class='buttons'>
    <button name='reset'  tabindex='4'>Reset</button>
    <button name='submit' tabindex='5'>Save</button>
   </div>
  </div><!-- userInput } -->
 </form><!-- ui-validation-form } -->

 <div id='account-info-avatar'
            title='Avatar Selection'
            style='display:none;'><!-- account-info-avatar { -->
  <div class='avatar-preview'>
   <div class='avatar-full'><img /></div>
   <div class='avatar-crop'><img /></div>
  </div>
  <div class='avatar-type-selection'>
   <ul>
     <li><a href='#avatar-type-file'>Upload</a></li>
     <li><a href='#avatar-type-url'>Url</a></li>
   </ul>
   <div id='avatar-type-file'>
    <div class='field'>
     <!-- label  for='avatarFile'>File</label -->
     <!-- form  action='<?= Connexions::url('/avatar-upload.php') ?> -->
     <form  action='?section=account&cmd=avatar'
            method='POST'
           enctype="multipart/form-data"><!-- account-info-avatar upload form { -->
      <input name='avatarFile' type='file' class='text' />
     </form><!-- account-info-avatar upload form } -->
    </div>
   </div>
   <div id='avatar-type-url'>
    <div class='field'>
     <label  for='avatarUrl'>URL</label>
     <input name='avatarUrl' type='text' class='text required' />
    </div>
   </div>
  </div>
  <div class='buttons'>
   <button name='cancel' tabindex='4'>Cancel</button>
   <button name='submit' tabindex='5'>Save</button>
  </div>
 </div><!-- account-info-avatar } -->

</div><!-- account-info } -->

<?php

/*
<!-- pre style='padding:1em; font-size:0.9em;'>
 <?= $this->viewer->debugDump() ?>
</pre -->
 */

