<?php
/** @file
 *
 *  Present a testing API for JsonRpc
 *
 */

$this->urlMethod = true;
$this->urlParams = true;
$this->jsonRpc   = true;
$this->seeAlso   = array(
    "the <a href='{$this->baseUrl('api/v2/')}'>API V2 Explorer</a>",
    "and the <a href='{$this->baseUrl('feeds/')}'>Version 1 Feeds</a>"
    . " (<a href='{$this->baseUrl('feeds/json/')}'>Json</a>, "
    .   "<a href='{$this->baseUrl('feeds/rss/')}'>RSS</a>, and "
    .   "<a href='{$this->baseUrl('feeds/atom/')}'>Atom</a>)");
echo $this->render('smd.phtml');
