<?php
/** @file
 *
 *  View script for PeopleController::index with incoming members:
 *      viewer              The Model_User instance representing the current
 *                          viewer;
 *      tagInfo             A Connexions_Set_Info instance containing
 *                          information about the requested tags.
 *
 *      paginator           A Zend_Paginator instance established for the
 *                          presentation of the current Model_UserSet;
 *      tagSet              The Connexions_Set instance established for the
 *                          presentation of tags related to the current
 *                          ModeL_UserSet;
 */
$baseUrl = $this->baseUrl('/'); //Connexions::url('/');
$links   = $this->headLink();
$links->appendStylesheet($baseUrl .'css/users.css');

$this->headTitle('People');

?>
<div class='columnHeader'>
 <div class='connexions_sprites user_bg
             ui-corner-left ui-corer-tr'>&nbsp;</div>
 <p>All People<?php
    if ( $this->tagInfo->hasValidItems())
        printf (" with tags '%s'", $this->tagInfo->validItems);
  ?>.
 </p>
</div>

<?php
/******************************************************************************
 * Render the HTML for the primary view using the HtmlUsers View Helper
 * that should have been prepared by the Controller.
 *
 */
echo $this->htmlUsers($this->paginator,
                      $this->viewer,
                      $this->tagInfo);

/******************************************************************************
 * Render the HTML for the right-column using the HtmlItemCloud View Helper
 * that should have been prepared by the Controller.
 *
 */
$this->layout()->right
      = "<div class='columnHeader'>"
      .  "<div class='connexions_sprites tag_bg "
      .              "ui-corner-left ui-corer-tr'>&nbsp;</div>"
      .  "<p>Tags shared by all the currently presented people.</p>"
      . "</div>"
      .  $this->htmlItemCloud()->render();
?>

<div class='error'><?= (@isset($this->error) ? $this->error : '') ?></div>
