<?php
/** @file
 *
 *  View script for PeopleController::index with incoming members:
 *      viewer      The Model_User instance representing the current viewer;
 *      owner       The owner of the current item set -- either a string or a
 *                  Model_User instance;
 *      tagInfo     A Connexions_Set_Info instance containing information about
 *                  the requested tags.
 *      userItems   The Model_UserItemSet representing the items to present.
 *      paginator   The paginator to use in presenting 'userItems'.
 *
 *      maxTags     Maximum number of tags to present;
 *      sortBy      Sort tags by (valid field of Model_Tag);
 *      sortOrder   Tag sort order.
 */

$this->headTitle('People');

?>
<p>Present People to  <?= $this->viewer ?>
<?php   if ( $this->tagInfo->hasValidItems())
            printf (" with tags '%s'", $this->tagInfo->validItems);
        else
            printf (", NO tags.");
?>
</p>

<?php
if ( @isset($this->users) )
{
    /* If $this->tagList is NOT set and we have 1 or more user, make use of the
     * 'users' Model_UserSet instance to retrieve the tags for these users.
     */
    if ((! @isset($this->tagList)) && (count($this->users) > 0))
    {
        // Create a tag set and then retrieve its Tag_ItemList adapter
        $tagSet        = new Model_TagSet( $this->users->userIds() );
        $tagSet->weightBy('user');

        $this->tagList = $tagSet->get_Tag_ItemList(0, $this->maxTags,
                                                   $this->tagInfo);
    }
}

if ( @isset($this->tagList))
{
    $time_start = microtime(true);

    /* Use the Connexions_View_Helper_HtmlTagCloud class to render the tag
     * cloud for $this->tagList.
     */
    $this->layout()->right = $this->htmlTagCloud($this->tagList,
                                                 $this->sortBy,
                                                 $this->sortOrder);


    $time_end   = microtime(true);
    $this->layout()->right .= sprintf ("%f seconds to render tag cloud<br />\n",
                                       $time_end - $time_start);
}

/* Present the pagination control, established by
 * Bootstrap.php::_initViewGlobal() to be rendered via:
 *      views/scripts/paginationControl.phtml
 */
echo $this->paginator;

if (count($this->paginator))
{
    // Present the items of the current page
    echo "<ul class='items'>\n";
    foreach ($this->paginator as $idex => $user)
    {
        /* Present the current item -- This should probably be via a view
         * partial like:
         *      view/scripts/user_listItem.phtml
         */
        echo $this->partial('user_listItem.phtml',
                            array(
                                'index' => $idex,
                                'user'  => $user
                            ));
    }
    echo "</ul>\n";
}

echo $this->paginator;

?>


<div class='error'><?= (@isset($this->error) ? $this->error : '') ?></div>
