<?php
/** @file
 *
 *  View script for PeopleController::index to render the sidebar content.
 *
 *  The Connexions_View_Helper_HtmlItemCloud helper MUST be initialized
 *  before this view is rendered.
 */

?>
<?= $this->render('sidebar.phtml') ?>

<div id='sidebar-tabs'>
 <ul>
  <li><a href='#sidebar-tags'  ><span>Tags</span></a></li>
  <!-- li><a href='#sidebar-people'><span>People</span></a></li -->
 </ul>
 <div id='sidebar-tags'>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites tag_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>Tags related to these bookmarks.</p>
  </div>
  <?= $this->htmlItemCloud()->render() ?>
 </div>

 <!-- div id='sidebar-people'>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites user_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>People that are in my network...</p>
  </div>
 </div -->
</div>
