<?php
/** @file
 *
 *  View script for IndexController::index to render the tags portion of the
 *  sidebar (i.e. the 'Tags' tab).
 *
 *  Incoming members:
 *      sidebarHelper   A View_Helper_HtmlSidebar instance configured with
 *                      information about the 'tags' sidebar pane;
 *
 *      url             The full url for the main controller of this page;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      tags            A Model_Set_Tag instance containing information about
 *                      any requested tags (i.e. tag restrictions);
 *      main            An array of settings for the main content panel:
 */

?>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites tag_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>Tags related to these people.</p>
  </div>
  <?php

    $config        = $this->sidebarHelper->getPane('tags');
    $htmlItemCloud = $this->htmlItemCloud($config);

    echo $htmlItemCloud->render();
