<?php
/** @file
 *
 *  View script for IndexController::index to render an JSON version of the
 *  main content.
 *
 *  Incoming members:
 *      rpc         The JsonRPC instance representing the request;
 *      paginator   The Zend_Paginator representing the items to be presented.
 *
 *  Sets the JsonRPC results for use by Bootstrap::jsonp_post to use in final
 *  rendering.
 */
Connexions_Profile::checkpoint('Connexions',
                               'IndexView Json rendering beginning');

$items = array();
foreach ($this->paginator as $item)
{
    array_push($items, $item->toArray(true));
}

$this->rpc->setResult( $items );

Connexions_Profile::checkpoint('Connexions',
                               'IndexView Json rendering COMPLETE');

