<?php
/** @file
 *
 *  View script for IndexController::index to render the tags portion of the
 *  sidebar (i.e. the 'Tags' tab).
 *
 *  The Connexions_View_Helper_HtmlItemCloud helper MUST be initialized
 *  before this view is rendered.
 */

$jQuery = $this->jQuery();

$jQuery->addOnLoad("init_sidebarTags();")
       ->javascriptCaptureStart();
?>

/*******************************************************
 * Initialize the Tags panel of the sidebar tab control
 *
 */
function init_sidebarTags()
{
    // Note: This assumes that init_sidebar() 
    var $tabs   = $('#sidebar-tabs');

    /* Bind to the 'submit' event of the DisplayOptions form.  When it fires,
     * the ui.optionGroups class that should be in control of the
     * DisplayOptions area should already have set the proper cookie values so
     * we can stop the event and perform an asynchronous retrieval of the new
     * content.
     */
    $tabs.find('#tagItems .displayOptions form').bind('submit.uioptiongroups',
        function(e) {
            e.preventDefault();
            e.stopPropagation();

            /* Re-load the tab content
             *
             * Note: this assumes that init_sidebar() (from sidebar.phtml) has
             *       been run to initialize the $tabs element as a ui.tabs
             *       widget.
             */
            $tabs.tabs('load', $tabs.tabs('option', 'selected'));
        }
    );
}
<?php
$jQuery->javascriptCaptureEnd();

?>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites tag_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>Tags related to these bookmarks.</p>
  </div>
  <?= $this->htmlItemCloud()->render() ?>

