<?php
/** @file
 *
 *  View script for IndexController::index to render the sidebar content.
 *
 */

$partUrl = $this->url . '?format=partial&part=';
?>
<?= $this->render('sidebar.phtml') ?>

<!-- Dynamically initialized tabs -->
<div id='sidebar-tabs'>
 <ul>
  <li><a href='<?= $partUrl .'sidebar-tags'   ?>'><span>Tags</span></a></li>
  <li><a href='<?= $partUrl .'sidebar-people' ?>'><span>People</span></a></li>
 </ul>
</div>

<!-- Statically initialized tabs
<div id='sidebar-tabs'>
 <ul>
  <li><a href='#sidebar-tags'  ><span>Tags</span></a></li>
  <li><a href='#sidebar-people'><span>People</span></a></li>
 </ul>

 <div id='sidebar-tags'>
  <?= $this->render('index/sidebar-tags.phtml') ?>
 </div>
 <div id='sidebar-people'>
  <?= $this->render('index/sidebar-people.phtml') ?>
 </div>
</div>
 -->
