<?php
/** @file
 *
 *  HTML rendering of the an "Item Cloud" as a list of items.
 *
 *  Incoming parameters:
 *      itemList        The Connexions_Model_Set_Adapter_ItemList instance
 *                      representing the items to present;
 *      weightName      The name of the weight field
 *                      (null == don't include weight);
 *      weightTitle     The title describing the weight field;
 *      titleName       The name of the title field;
 *      titleTitle      The title describing the title field;
 *      itemType        The type of item
 *                      (View_Helper_HtmlItemCloud::ITEM_TYPE_USER |
 *                                                  ITEM_TYPE_ITEM);
 *      showControls    Whether or not management controls should be presented
 *                      (i.e. the viewer is also the owner of the items being
 *                            presented).
 *                      This is used primarily when
 *                          itemType === ITEM_TYPE_ITEM.
 *
 */
$itemList      =& $this->itemList;

$includeWeight =  ($this->weightName !== null);
$titleTitle    =  ($this->titleTitle !== null
                    ? $this->titleTitle
                    : ($this->itemType ===
                            View_Helper_HtmlItemCloud::ITEM_TYPE_USER
                        ? 'User'
                        : 'Item'
                    )
                  );
$weightTitle   =  ($this->weightTitle !== null
                    ? $this->weightTitle
                    : 'Weight');

/*
Connexions::log('view/scripts/itemList: '
                . 'showControls[ %s ], '
                . 'itemType[ %s ], '
                . 'includeWeight[ %s ], '
                . 'title Title[ %s ] / Weight[ %s ]',
                Connexions::varExport($this->showControls),
                ($itemType === View_Helper_HtmlItemCloud::ITEM_TYPE_USER
                    ? 'user'
                    : 'item'),
                Connexions::varExport($includeWeight),
                $titleTitle,
                $weightTitle);
// */
?>
<ul class='Item_List'>
 <li class='header'><span class='item'><?= $titleTitle ?></span><?php

if ($includeWeight)
{
    ?><span class='itemCount'><?= $weightTitle ?></span><?php
}

?></li><?php

$idex = 0;
foreach ($itemList as $item)
{
    $oddEven = (++$idex % 2 ? 'even' : 'odd');
    $url     = $item->getParam('url');
    $weight  = number_format(round($item->getWeight()));
    $title   = $item->getTitle();

    ?><li class='<?= $oddEven ?>'><?php

    $img = '';
    if ($item instanceof Model_User)
    {
        // Include the user's avatar
        $img = '<div class="img icon-highlight">';
        if (! empty($user->pictureUrl))
        {
            $img .= "<img src='{$user->pictureUrl}' />";
        }
        else
        {
            $img .= "<div class='ui-icon ui-icon-person'>&mbsp;</div>";
        }
        $img .= '</div>';
    }

    if (empty($url))
    {
        ?><span class='item'><?= $img . $title ?></span><?php

    }
    else
    {
        ?><a class='item' 
              href='<?= htmlSpecialChars($url) ?>'><?= $img . $title ?></a><?php
    }

    if ($includeWeight)
    {
        $elTitle = ($this->weightTitle !== null
                        ? " title='". htmlspecialchars($this->wieghtTitle) ."'"
                        : '');

        ?><span class='itemCount'<?= $elTitle ?>><?= $weight ?></span><?php
    }

    ?></li><?php
}

?>
</ul>
