<?php
/** @file
 *
 *  Generic sidebar view script.
 *
 *  Adds an 'init_sidebar()' on-load script to initialize the '#sidebar-tabs'
 *  DOM element as a ui.tabs widget.
 */

$jQuery = $this->jQuery();

$jQuery->addOnLoad("init_sidebar();")
       ->javascriptCaptureStart();
?>

/************************************************
 * Initialize the sidebar tab control
 *
 */
function init_sidebar()
{
    /* Convert the '#sidebar-tabs' DOM element to a ui.tabs widget that will
     * automatically mask the tab panel when performing an AJAX load.
     */
    var $tabs   = $('#sidebar-tabs');
    var $tab    = null;
    $tabs.tabs({
        cache:      true,
        cookie:     'sidebarTab',
        ajaxOptions:{
            beforeSend: function() {
                // Mask the tab panel area...
                var sel = $tabs.tabs('option', 'selected');
                $tab = $tabs.find('.ui-tabs-panel').eq(sel);

                $tab.mask();
            },
            complete: function() {
                // Unmask the tab panel area...
                $tab.unmask();
            }
        }
    } );
}
<?php
$jQuery->javascriptCaptureEnd();


