<?php
/** @file
 *
 *  Generic user view script.
 *
 *  Incoming members:
 *      user            The Model_User instance to render.
 *      viewer          The Model_User instance to render.
 *      showParts       An array indicating which portions of the user record
 *                      to present;
 *      maxTags         The maximum number of tags to present for a user [ 5 ];
 */

if (! isset($this->showParts))
{
    // The portions of the user information to present
    $this->noAvatar  = $this->baseUrl('/images/User.gif');
    $this->showParts = array(
        'user:stats'                => true,
        'user:stats:countItems'     => true,
        'user:stats:countTags'      => true,
        'user:data:avatar'          => true,
        'user:data:relation'        => true,
        'user:data:userId'          => true,
        'user:data:fullName'        => true,
        'user:data:email'           => true,
        'user:data:tags'            => true,
        'user:data:dates'           => true,
        'user:data:dates:lastVisit' => true,
    );
}

$jQuery = $this->jQuery();
$jQuery->addOnLoad('$.sidebar_user_onLoad();')
       ->javascriptCaptureStart();
?>
(function($) {
    $.sidebar_user_onLoad = function() {
        // Activate the user item.
        $('#usersList ul.sidebar li > form').user();
    };
}(jQuery));

<?php
$jQuery->javascriptCaptureEnd();

?>
<div id='usersList' class='userItems single-user'>
  <div class='cloudRelation connexions_sprites relation_ltr'>&nbsp;</div>
  <ul class='users sidebar'>
    <?= $this->partial('user.phtml', $this) ?>
    <br class='clear' />
  </ul>
</div>
