<?php
/** @file
 *
 *  Render a single userItem.
 *
 *  $this implements the Zend_View_Interface and has at least the following
 *  members/methods:
 *      userItem        The Model_UserItem instance to present.
 *      viewer          The Model_User     instance of the current viewer
 */
if ((! @isset($this->userItem)) ||
    (! $this->userItem instanceof Model_UserItem))
{
    return;
}

/*
printf ("<li class='item'>Item %s: %s </li>\n",
        (@isset($this->index) ? $this->index : ''),
        $this->userItem->debugDump());
*/
$item    =& $this->userItem;

$isOwner = ( ($this->viewer && ($item->user->userId === $this->viewer->userId))
                ? true
                : false );

$itemClasses = array();
if ($isOwner)           array_push($itemClasses, 'mine');
else                    array_push($itemClasses, 'other');

if ($item->isFavorite)  array_push($itemClasses, 'favorite');

if ($item->isPrivate)   array_push($itemClasses, 'private');

?>
<li class='item <?php echo implode(' ', $itemClasses) ?>'>
 <div class='status'>
  <?php
    if ($isOwner)
    {
        printf (  "<div class='favorite'>"
                .  "<input type='checkbox' name='isFavorite' value='true' %s/>"
                . "</div>"
                . "<div class='private'>"
                .  "<input type='checkbox' name='isPrivate' value='true' %s/>"
                . "</div>",
                ($item->isFavorite ? " checked='true'" : ""),
                ($item->isPrivate  ? " checked='true'" : "") );
    }

  ?>
 </div>
 <div class='meta'>
  <?php
    printf (  "<a class='countTaggers' href='%s'>%d</a>"
            . "<div class='rating'>"        // rating {
            .  "<div class='stars'>",       // stars {
            $this->url(array('action'   => 'url',
                             'urlHash'  => $item->item->urlHash)),
            $item->item->userCount);

    if ( $item->item->ratingCount > 0 )
    {
        printf("<div class='average%s'>",   // stars .average {
               ($isOwner ? " average-owner"
                         : ""));

        $avgRating = $item->item->ratingSum / $item->item->ratingCount;
        $rating    = ceil( ($avgRating * 2.0) );

        for ($rdex = 0; $rdex < 11; $rdex++)
        {
            printf ("<input type='radio' name='rating' value='%s' "
                    .                              "disabled='true'%s/>",
                    $rdex,
                    ($rating == $rdex
                        ? "checked='true' "
                        : ""));
        }

        echo "</div>";                      // stars .average }
    }

    if ( $isOwner )
    {
        $rating = $item->item->rating;

        echo "<div class='owner'>";         // stars .owner {

        for ($rdex = 0; $rdex < 6; $rdex++)
        {
            printf ("<input type='radio' name='rating' value='%s' %s/>",
                    $rdex,
                    ($rating == $rdex
                        ? "checked='true' "
                        : ""));
        }

        echo "</div>";                      // stars .owner }
    }

    echo       "</div>";    // stars }

    if ( $item->item->ratingCount > 0 )
    {
        printf(   "<div class='meta'>"
               .   "<span class='count'>%d</span> raters, "
               .   "<span class='average'>%3.2f</span> avg."
               .  "</div>",
               $item->item->ratingCount,
               $item->item->ratingSum / $item->item->ratingCount);
    }


    echo  "</div>";     // rating }
  ?>
 </div>
 <div class='data'>
  <h4 class='itemName'>
   <?php
    printf ("<a href='%s' title='%s'>%s</a>",
            $item->item->url, $item->item->urlHash,
            htmlspecialchars($item->name));
   ?>
   <div class='control'>
    <?php
    if ($isOwner)
    {
        printf (   "<a class='item-edit'   href='%s'>edit</a> | "
                .  "<a class='item-delete' href='%s'>delete</a>",
                $this->url(array('action' => 'itemEdit',
                                 'item'   => $item->itemId)),
                $this->url(array('action' => 'itemDelete',
                                 'item'   => $item->itemId)) );
    }
    else
    {
        $saveUrl = $this->url(array('action'       => 'post'))
                 .      '?name='.        urlencode($item->name)
                 .      '&url='.         urlencode($item->item->url)
                 .      '&description='. urlencode($item->description)
                 .      '&tags='.        urlencode($item->tags->__toString());

        printf (   "<a class='item-save'   href='%s'>save</a>",
                $saveUrl);
    }
    ?>
   </div>
  </h4>
  <div class='url'>
  <?php
    printf ("<a href='%s' title='%s'>%s</a>",
            $item->item->url, $item->item->urlHash, $item->item->url);
  ?>
  </div>
  <br class='clear' />
  <?php
    if (! @empty($item->description) )
    {
        printf ("<div class='description'>%s</div>",
                htmlspecialchars($item->description));
    }
  ?>
  <div class='userName'>
   <?php
    printf ("<a href='%s' title='%s'>%s</a>",
            $this->url(array('action'   => $item->user->name)),
            $item->user->fullName, $item->user->name);
  
   ?>
  </div>
  <ul class='tags'>
   <?php
    foreach ($item->tags as $tag)
    {
        printf ("<li class='tag ui-state-default'><a href='%s'>%s</a></li>",
                $this->url(array('action'   => 'tagged',
                                 'tag'      => $tag->tag)), $tag->tag);
    }
   ?>
  </ul>
  <br class='clear' />
  <div class='dates'>
   <?php
    printf (  "<div class='tagged'>%s</div>"
            . "<div class='updated'>%s</div>",
            $item->taggedOn,
            $item->updatedOn);
   ?>
  </div>
  <br class='clear' />
 </div>
</li>
