<?php
/** @file
 *
 *  View script for TagsController::index with incoming members:
 *      viewer              The Model_User instance representing the current
 *                          viewer;
 *      userInfo            A Connexions_Set_Info instance containing
 *                          information about the requested users;
 *
 *      tagList             The Zend_Tag_ItemList instance established for the
 *                          presentation of current Model_TagSet;
 *      sbCloudHelper       The Connexions_View_Helper_HtmlItemCloud instance
 *                          established for the cloud presentation of users
 *                          related to the current ModeL_TagSet;
 */

$this->headTitle('Tags');

?>
<div class='columnHeader'>
 <div class='connexions_sprites tag_bg
             ui-corner-left ui-corer-tr'>&nbsp;</div>
 <p>
  <?php
    if ( $this->userInfo && $this->userInfo->hasValidItems())
    {
            if (count($this->userInfo->validIds) == 1)
                echo "All tags used by user ";
            else
                echo "Those tags in common to users ";

            echo "'{$this->userInfo->validItems}'.";
    }
    else
        printf ("All tags.");
  ?>
 </p>
</div>

<?php
/******************************************************************************
 * Render the HTML for the primary view using the primary HtmlItemCloud View
 * Helper that should have been prepared by the Controller.
 *
 */
$uiCloud = $this->htmlItemCloud();

/*
Connexions::log("tags:: Render main cloud: "
                    . "Style[ {$uiCloud->getStyle()} ], "
                    . "HighlightCount[ "
                    .       $uiCloud->getHighlightCount() ." ], "
                    . "SortBy[ {$uiCloud->getSortBy()} ], "
                    . "SortOrder[ {$uiCloud->getSortOrder()} ]");
// */

/* Present the current scope information
 *  The itemSet connected with the uiCloud instance SHOULD be a Zend_Paginator
 *  in this instance.
 */
echo $this->htmlItemScope($uiCloud->getItemSet(),
                          $this->userInfo);

echo $uiCloud->render();    //$this->tagList);

/******************************************************************************
 * Render the HTML for the right-column using the secondary HtmlItemCloud View
 * Helper that should have been prepared by the Controller.
 *
 */
if ( @isset($this->sbCloudHelper))
{
    /*
    Connexions::log("tags:: Render sidebar cloud: "
                        . "Style[ {$this->sbCloudHelper->getStyle()} ], "
                        . "HighlightCount[ "
                        .   $this->sbCloudHelper->getHighlightCount() ." ], "
                        . "SortBy[ {$this->sbCloudHelper->getSortBy()} ], "
                        . "SortOrder[ "
                        .   $this->sbCloudHelper->getSortOrder() ." ]");
    // */

    $this->layout()->right
        = "<div class='columnHeader'>"
        .  "<div class='connexions_sprites user_bg "
        .              "ui-corner-left ui-corer-tr'>&nbsp;</div>"
        .  "<p>"
        .   "All people that have at least one of "
        .   "the currently presented tags."
        .  "</p>"
        . "</div>"
        . $this->sbCloudHelper->render();
}

?>

<div class='error'><?= (@isset($this->error) ? $this->error : '') ?></div>
