<?php
/** @file
 *
 *  View script for TagsController::index to render the sidebar content.
 *
 *  Incoming members:
 *      sbCloudHelper       The Connexions_View_Helper_HtmlItemCloud instance
 *                          established for the cloud presentation of users
 *                          related to the current ModeL_TagSet;
 */

?>
<?= $this->render('sidebar.phtml') ?>

<div id='sidebar-tabs'><!-- { -->
 <ul>
  <!-- li><a href='#sidebar-tags'  ><span>Tags</span></a></li -->
  <li><a href='#sidebar-people'><span>People</span></a></li>
 </ul>
 <!-- div id='sidebar-tags'>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites tag_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>???</p>
  </div>
 </div -->

 <div id='sidebar-people'>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites user_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>All people that have at least one of the currently presented tags.</p>
  </div>
  <?= $this->sbCloudHelper->render() ?>
 </div>
</div><!-- sidebar-tabs } -->

