<?php
/** @file
 *
 *  View script for TagsController::index to render the tags portion of the
 *  sidebar (i.e. the 'Tags' tab).
 *
 *  Incoming members:
 *      url             The full url for the main controller of this page;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      tags            A Model_Set_Tag instance containing information about
 *                      any requested tags (i.e. tag restrictions);
 *      item            The item being presented in the main view;
 *
 *      main            An array of settings for the main content panel:
 *      sidebar         An array of settings for the sidebar:
 */

?>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites tag_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>Summary of
   <?php
    $nUsers = count($this->users);
    if ( $nUsers > 0)
        printf ("tags used by<br />%s %d user%s",
                ($nUsers === 1 ? 'this' : 'these'),
                $nUsers,
                ($nUsers === 1 ? ''     : 's'));
    else
        echo "all tags";

    ?>.</p>
  </div>
  <?php

    $config        = $this->sidebarHelper->getPane('tags');
    $htmlItemCloud = $this->htmlItemCloud($config);

    echo $htmlItemCloud->render();
