<?php
//$this->headLink()->appendStylesheet(Connexions::url('/css/auth.css'));
//$this->headLink()->appendStylesheet($this->baseUrl('css/auth.css'));
$this->headTitle('Sign In');

$jQuery = $this->jQuery();
$jQuery->addStylesheet($this->baseUrl('css/auth.css'))
       ->addOnLoad('$("#auth form").validationForm({'
                   .    'submitSelector:"button[name=method]"});');
?>
<div class="line"><!-- { -->
 <div id="auth" class='ui-validation-form ribbon-form'>
  <div class='context-ribbon'>&nbsp;</div>
  <div class="legend unit"><!-- { -->
   <h1>Sign in</h1>
   <p>
    or <?= Connexions::anchor('/auth/register', 'Join now') ?>
   </p>
   <div class='status<?= (@isset($this->error) ? ' error' : '') ?>'>
    <?= (@isset($this->error) ? $this->error : '') ?>
   </div>
  </div><!-- legend } -->
  <div class="userInput unit"><!-- { -->
   <form method='post'>
    <div class='field'>
     <label for='username'>User name</label>
     <input type='text' class='text required' name='username'
                        value='<?= $this->username ?>'
                     tabindex='1' />
     <div class='ui-field-info'>
      <div class='ui-field-status'></div>
     </div>
    </div>
    <div class='field'>
     <label for='password' >Password</label>
     <input type='password' class='text required'
            name='password'
                         tabindex='2' />
     <div class='ui-field-info'>
      <div class='ui-field-status'></div>
     </div>
    </div>
    <div class='field buttons'>
     <button name='method' tabindex='3' value='userpassword'>
      Sign-in
     </button>
    </div>
   </form>
 
   <? if ($this->welcome)   echo "Welcome!!<br />"; ?>
  </div><!-- userInput } -->
 </div>
</div><!-- line } -->
