#!/usr/bin/env php
<?php
define('CLI_DIR', realpath(dirname(__FILE__)));

require_once(CLI_DIR. '/bootstrap.php');
$prog = array_shift($argv);

$svc = Connexions_Service::factory('Service_Item');
foreach ($argv as $itemId)
{
    $item = $svc->find($itemId);
    printf ("itemId[ %s ]: %s\n",
            $itemId,
            ($item instanceof Model_Item
                ? $item->debugDump()
                : "NOT FOUND") );
}
