#!/usr/bin/env php
<?php
define('CLI_DIR', realpath(dirname(__FILE__)));

require_once(CLI_DIR. '/bootstrap.php');
$prog = array_shift($argv);

$svc = Connexions_Service::factory('Service_User');
foreach ($argv as $userId)
{
    $user = $svc->find($userId);
    printf ("userId[ %s ]: %s\n",
            $userId,
            ($user instanceof Model_User
                ? $user->debugDump()
                : "NOT FOUND") );
}
