<?php
$config   =  Zend_Registry::get('config');
$contact  =& $config->contact;
$url      =  $this->baseUrl('help/about');

?>
<h3><span>Connexions</span></h3>
<p>Connexions is about collecting, organizing and sharing your favorite
resources from across the net.</p>

<p>We are a small team with a passion for design, collaboration, and generally
the creation of tools to help you get your job done effectively.</p>
