<?php
/** @file
 *
 *  Render the main settings page.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *
 *      section         The settings section;
 *      cmd             The specific settings command;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'cmds':     [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 */

$this->headTitle('Settings');

$this->headLink()->appendStylesheet($this->baseUrl('/css/settings.css'));

$jQuery = $this->jQuery();
$jQuery->addOnLoad("settings_onLoad();")
       ->javascriptCaptureStart();
?>
/************************************************
 * Initialize the settings tabs
 *
 */
function settings_onLoad()
{
    var $el         = $('#settings');
    var $tab        = null;

    var _sendPre    = function() {
        // Mask the tab panel area...
        var sel = $el.tabs('option', 'selected');
        $tab = $el.find('.ui-tabs-panel').eq(sel);

        $tab.mask();
    };

    var _sendPost   = function() {
        $tab.unmask();
    };

    $el.tabs({
        cache:  true,
        cookie: 'settings',
        ajaxOptions: {
            beforeSend: _sendPre,
            complete:   _sendPost
        }
    });

    $el.find('.collapsable').collapsable({
        cache:  true,
        cookie: 'settings',
        ajaxOptions: {
            beforeSend: _sendPre,
            complete:   _sendPost
        }
    });
}

<?php
    $jQuery->javascriptCaptureEnd();

?>
<p>Present the Settings for <?= $this->viewer ?>:<br />
      section[ <?= $this->section ?>], cmd[ <?= $this->cmd ?> ]
</p>

<div id='settings' class='settings'>
 <ul>
<?php
    $paneHtml = '';
    foreach ($this->sections as $id => $section)
    {
        /*
        $paneUrl = $this->view->url
                 .  '?format=partial'
                 .  '&part='. $section['script'];
        */
        $paneUrl = "#{$id}";
        $paneCss = (! empty($section['cssClass'])
                        ? $section['cssClass']
                        : $id);

        ?>
  <li><a href='<?= $paneUrl ?>'><span><?= $section['title'] ?></span></a></li><?php

        $paneHtml .= "<div id='{$id}'>"
                  .    "<ul id='{$id}-cmds' class='{$paneCss}'>";
        foreach ($section['cmds'] as $cmd)
        {
            $cmdId  = $id .'-'. preg_replace('/\s+/', '_',
                                             strtolower($cmd['title']));
            $state  = ($cmd['expanded'] === true
                        ? 'expanded'
                        : 'collapsed');

            /*
            Connexions::log("view/scripts/settings/index.phtml: "
                            . "section[ %s ], cmd[ %s ]",
                            $id, Connexions::varExport($cmd));
            // */

            $sectHtml  = '';
            $paneHtml .= "<li class='collapsable {$cmdId}'>"
                      .   "<h3 class='toggle {$state}'>";

            if (isset($cmd['async']) && ($cmd['async'] === true))
            {
                $cmdUrl = $this->view->url
                        .   '?format=partial'
                        .   '&part='. $cmd['script'];

                /*
                Connexions::log("view/scripts/settings/index.phtml: "
                                . "section[ %s ], cmd[ %s ]: url[ %s ]",
                                $id, $cmd['title'], $cmdUrl);
                // */

                $paneHtml .= "<a href='{$cmdUrl}'>{$cmd['title']}</a>";
            }
            else
            {
                $script    = 'settings/'. $cmd['script'] .'.phtml';
                $paneHtml .= "<span>{$cmd['title']}</span>";

                $sectHtml  = "<div class='content'>"
                           .    $this->render($script)
                           . "</div>";
            }

            $paneHtml .=  "</h3>"
                      .  $sectHtml
                      .  "</li>";
        }
        $paneHtml .=  "</ul>"
                  .  "</div>";
    }

?>
 </ul>
 <?= $paneHtml ?>
</div>

<div class='error'><?= (@isset($this->error) ? $this->error : '') ?></div>
