<?php
/** @file
 *
 *  Render the Bookmarks Export section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *
 *      section         The settings section;
 *      cmd             The specific settings command;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'cmds':     [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 */

$jQuery = $this->jQuery();
$jQuery->addOnLoad('$.bookmark_export_onLoad();')
       ->javascriptCaptureStart();
?>
(function($) {

    $.bookmark_export_onLoad = function() {
        $('#bookmark-export').find('form input[type=submit]').button({
            priority:   'primary',
            enabled:    true
        });
    };

}(jQuery));
<?php
$jQuery->javascriptCaptureEnd();

/* Set 'streaming=true' below so the post-bookmarks-export.pthml view script
 * will be rendered directly with no layout.
 */
?>
<div id='bookmark-export'><!-- bookmark-export { -->
 <form  action='?format=partial&part=post-bookmarks-export&streaming=true'
        method='POST'
       enctype="multipart/form-data"><!-- form { -->
  <div class='section'><!-- section { -->
   <h3>Export / Download your Connexions Bookmarks</h3>
   <p id='bookmark-export-browser-instructions'>
     This tool generates an HTML version of your bookmarks that is
     understandable by most browsers.  You can then save the generated page as
     HTML and import it into your browser, or any other application that
     accepts bookmarks in a standard format.
   </p>
   <div class='field'><!-- field { -->
    <input type='checkbox'
             id='includeTags'
           name='includeTags' checked='true' /><label for='includeTags'>Include tags?</label>
   </div><!-- field } -->

   <div class='field'><!-- field { -->
    <input type='checkbox'
             id='includeMeta'
           name='includeMeta' checked='true' /><label for='includeMeta'>Include notes, privacy, favorite, and rating information?</label>
   </div><!-- field } -->
  </div><!-- section } -->
  <div class='buttons'><!-- buttons { -->
   <!-- button name='submit'>Export</button -->
   <input type='submit' name='submit' value='Export' />
  </div><!-- buttons } -->
 </form><!-- form } -->

 <div class='results-section section' style='display:none'>
  <h3>Export Results:</h3>
  <!-- Target for form submission / bookmark file upload / export results -->
  <iframe id='bookmark-export-results'
        name='bookmark-export-results'
         src='about:blank'></iframe>
 </div>
</div><!-- bookmark-export } -->
