<?php
/** @file
 *
 *  Render the Account Credentials section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      credentials     The Model_Set_UserAuth instance representing all
 *                      credentials for the current viewer;
 *
 *      section         The settings section;
 *      setting         The specific setting;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'settings': [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 */

$jQuery = $this->jQuery();
$jQuery->addOnLoad('$.account_credentials_onLoad();')
       ->javascriptCaptureStart();
?>
(function($) {

    $.account_credentials_onLoad = function() {
        $('#account-credentials .ui-validation-form').credentials();
    };

}(jQuery));
<?php
$jQuery->javascriptCaptureEnd();

//$ar   = $this->viewer->getAuthResult();
//$ar->getAuthType());

?>
<ul id='account-credentials' class='credentials'>
 <form class='ui-validation-form'>
  <?php

    // $this->credentials->debugDump();
    foreach ($this->credentials as $auth)
    {
        ?>
  <li class='<?= $auth->authType ?>'>
   <!-- <?= $auth->debugDump() ?> -->
   <input type='hidden'
          name='userAuthId'
         value='<?= $auth->userAuthId ?>' />
   <div class='type <?= $auth->authType ?>'
        title='<?= $auth->authType ?>'><?= $auth->authType ?></div>
   <div class='field name'>
    <label  for='name'>Name</label>
    <input type='text'
           name='name'
          class='text'
          value='<?= $auth->name ?>' />
   </div>
   <div class='field credential'>
    <label  for='credential'>Credential</label>
    <input type='<?= ($auth->authType === 'password' ? 'password' : 'text') ?>'
           name='credential'
          class='text required'
          value='<?= $auth->credential ?>' />
    </div>
   <div class='field control'>
    <a class='delete' href='#'>delete</a>
   </div>
  </li>
        <?php
    }

 ?>
  <li class='buttons'>
   <div class='control'>
    <a class='add' href='#'>add</a>
   </div>
   <div class='warning'>
    <p><span class='title'>Warning:</span>Do NOT delete all credentials or,
    once you've signed out or your current authenticated session expires, you
    will no longer be able to sign in.</p>
   </div>
   <button name='submit'>Save</button>
   <button name='reset'>Reset</button>
   <br class='clear' />
  </li>
  <!--
  <li class='warning'>
   <p><span class='title'>Warning:</span>Do NOT delete all credentials or,
   once you've signed out or your current authenticated session expires, you
   will no longer be able to sign in.</p>
  </li>
  -->
 </form>
</ul>
