<?php
/** @file
 *
 *  Render the Account Info section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *
 *      section         The settings section;
 *      cmd             The specific settings command;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'cmds':     [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 */

$avatar = (empty($this->viewer->pictureUrl)
            ? "<div class='connexions_sprites user_bg'>&nbsp;</div>"
            : "<img src='{$this->viewer->pictureUrl}' />" );

$jQuery = $this->jQuery();
$jQuery->addOnLoad('$.account_info_onLoad();')
       ->javascriptCaptureStart();
?>
(function($) {
    var api     = null;
    var $ai     = null;
    var $submit = null;

    function account_info_submit()
    {
        var $fullName   = $ai.find('.user-fullName input');
        var $email      = $ai.find('.user-email input');
        var $profile    = $ai.find('.user-profile input');
        var $avatar     = $ai.find('.avatar img');
        var params  = {
            'fullName':   $fullName.val(),
            'email':      $email.val(),
            'profile':    $profile.val()
        };

        if ($avatar.length > 0)
        {
            params.pictureUrl = $avatar.attr('src');
        }

        $ai.mask();

        // Perform an json-rpc call to save the new information.
        $.jsonRpc(api.jsonRpc, 'user.update', params, {
            success: function(data) {
                if ( (! data) || (data.error !== null))
                {
                    $.notify({
                        title:  'Information Update failed',
                        text:   '<p class="error">'
                              +   (data ? data.error.message : '')
                              + '</p>'
                    });
                }
                else
                {
                    $.notify({
                        title:  'Information Updated',
                        text:   ''
                    });
                }
            },
            error: function(req, textStatus, err) {
                $.notify({
                    title:  'Information Update failed',
                    text:   '<p class="error">'
                          +   textStatus
                          + '</p>'
                });
            },
            complete: function(req, textStatus) {
                $ai.unmask();
                $submit.button('disable');
            }
        });
    }

    $.account_info_onLoad = function() {
        api     = $.registry('api');
        $ai     = $('#account-info .ui-validation-form');
        $submit = $ai.find('button[name=submit]');
        
        $ai.validationForm({hideLabels:false})
                /*
                .bind('validation_change', function(e) {
                    $submit.button(($ai.validationForm('hasChanged') &&
                                    $ai.validationForm('isValid')
                                        ? 'enable'
                                        : 'disable'));
                })
                */
                .bind('submit', function(e) {
                    e.preventDefault();
                    e.stopPropagation();

                    if ($ai.validationForm('isValid'))
                    {
                        account_info_submit();
                    }
                });
        //$submit.button('disable');

        $ai.find('.avatar div,.avatar img')
                .attr('title', 'click-to-edit')
                .bind('click', function() {
                    // Popup an image selection dialog
                });
    };

}(jQuery));
<?php
$jQuery->javascriptCaptureEnd();


?>
<div id='account-info' class='line'>
 <form class='ui-validation-form'>
  <div class='legend unit'>
   <div class='avatar ui-corner-all'>
    <?= $avatar ?>
   </div>
   <div class='user-name' title='User name'>
    <?= $this->viewer->name ?>
   </div>
   <div class='user-date' title='Last visit'>
    <?= substr($this->viewer->lastVisit, 0, 10) ?>
   </div>
  </div>
  <div class='userInput lastUnit'>
   <h3 class='user-fullName field' title='Full Name'>
    <label for='fullName'>Full Name</label>
    <input name='fullName' type='text' class='text required' autocomplete='off'
          value='<?= $this->viewer->fullName ?>' tabindex='1' />
   </h3>
   <div class='user-email field' title='email address'>
    <label  for='email'>email</label>
    <input name='email' type='text' class='text required' autocomplete='off'
          value='<?= $this->viewer->email ?>' tabindex='2' />
   </div>
   <div class='user-profile field' title='Profile url'>
    <label  for='profile'>Profile url</label>
    <input name='profile' type='text' class='text' autocomplete='off'
          value='<?= $this->viewer->profile ?>' tabindex='3' />
   </div>
   <div class='buttons'>
    <button name='reset'  tabindex='4'>Reset</button>
    <button name='submit' tabindex='5'>Save</button>
    <!-- button name='cancel' tabindex='5'>Cancel</button -->
   </div>
  </div>
 </form>
</div>

<!-- pre style='padding:1em; font-size:0.9em;'>
 <?= $this->viewer->debugDump() ?>
</pre -->
