<?php
/** @file
 *
 *  Render the People Network section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *
 *      section         The settings section;
 *      setting         The specific setting;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'settings': [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 *
 *      main            An array of settings for the main body:
 *          namespace       The cookie/parameters/settings namespace for
 *                          the the main body;
 *          viewer          The Model_User instance representing the current
 *                          viewer (typically a reference to $view->viewer);
 *          group           A Model_Group instance containing information
 *                          about the Network of 'viewer';
 *          panePartial     The partial script to use to render the paginated
 *                          contents of 'group';
 *
 *          displayStyle    Indicates the current presentation style --
 *                          if this is an array, the style is 'custom';
 *          perPage         The number of results on a single page;
 *          page            The desired page of results;
 *          sortBy          The desired sort field;
 *          sortOrder       The desired sort order;
 *          highlightCount  The number of tags to highlight;
 *
 *          showRelation    Show the relation indicator?;
 *          itemType        The type of item being presented
 *                          (View_Helper_HtmlItemCloud::ITEM_TYPE_*);
 */
$config      = &$this->main;
$namespace   = $config['namespace'];
$panePartial = $config['panePartial'];

/*
Connexions::log('views/scripts/settings/main-people-network.phtml: '
                . 'namespace[ %s ], panePartial[ %s ]',
                $namespace, $panePartial);
// */

$visibility = ($this->main['group']
                ? $this->main['group']->visibility
                : 'private');

/*
Connexions::log('views/scripts/settings/main-people-network.phtml: '
                . 'group[ %s ], visibility[ %s ]',
                Connexions::varExport($this->main['group']),
                Connexions::varExport($visibility));
// */


// Top-level, static, non-paginated content
$id = 'people-network';
?>
<div id='<?= $id ?>'><!-- people-network { -->
 <div class='networkControl'>
   <div class='networkAdd ui-form'>
     <div class='field'>
      <label for='networkAdd-input'>Follow User</label>
      <input  id='networkAdd-input' type='text' class='text' />
     </div>
     <button name='submit'>add</button>
   </div>
   <div class='networkVisibility'>
     <div id='visibility' class='options'>
       <input   id='visibility-private'
              type='radio'
              name='visibility'
              <?= ($visibility === 'private'
                    ? "checked='checked'"
                    : '') ?>
             title='visibility: only you'
             value='private' />
       <label  for='visibility-private'
             title='visibility: only you'>Private</label>
       <input   id='visibility-public'
              type='radio'
              name='visibility'
              <?= ($visibility === 'public'
                    ? "checked='checked'"
                    : '') ?>
             title='visibility: everyone'
             value='public' />
       <label  for='visibility-public'
             title='visibility: everyone'>Public</label>
       <input   id='visibility-group'
              type='radio'
              name='visibility'
              <?= ($visibility === 'group'
                    ? "checked='checked'"
                    : '') ?>
             title='visibility: your network'
             value='group' />
       <label  for='visibility-group'
             title='visibility: your network'>These People</label>
     </div>
     <div class='label'>network visibility</div>
   </div>
 </div>
 <!-- Dynamic, paginated content -->
 <?= $this->partial('settings/'. $panePartial .'.phtml', $this) ?>
</div><!-- people-network } -->
<?php

$jsWait = false;
$jsLoad = "$('#{$id} .networkControl').networkControl();";
if ($jsWait === false)
{
    // Instantiate the Javascript widget immediately
    ?>
<script type='text/javascript'>
(function($) {
    <?= $jsLoad ?>
 }(jQuery));
</script>
    <?php
}
else
{
    // Wait until DOM-reay to instantiate the Javascript widget
    $this->jQuery()->addOnLoad( $jsLoad );
}
