<?php
/** @file
 *
 *  Render the Account Info section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *
 *      section         The settings section;
 *      cmd             The specific settings command;
 *      sections        An array of avaialble sections and commands of the
 *                      form:
 *                          {section: {
 *                              'title':    section title,
 *                              'script':   section render script
 *                              'cmds':     [
 *                                  {'title':   command title,
 *                                   'script':  command render script},
 *                                  ...
 *                              ],
 *                           },
 *                           ...
 *                          }
 */

$avatar = (empty($this->viewer->pictureUrl)
            ? "<div class='connexions_sprites user_bg'>&nbsp;</div>"
            : "<img src='{$this->viewer->pictureUrl}' />" );

?>
<form class='person'>
  <div style='float:left;'>
   <div class='avatar ui-corner-all'>
    <?= $avatar ?>
   </div>
   <div class='user-name'>
    <?= $this->viewer->name ?>
   </div>
   <div class='user-date'>
    <?= substr($this->viewer->lastVisit, 0, 10) ?>
   </div>
  </div>
  <div style='float:left;'>
   <h3 class='user-fullName field'>
    <label for='fullName'>Full Name</label>
    <input name='fullName' type='text' class='text' autocomplete='off'
          value='<?= $this->viewer->fullName ?>' tabindex='1' />
   </h3>
   <div class='user-email field'>
    <label  for='email'>email</label>
    <input name='email' type='text' class='text' autocomplete='off'
          value='<?= $this->viewer->email ?>' tabindex='2' />
   </div>
   <div class='user-profile'>
    <label  for='profile'>Profile url</label>
    <input name='profile' type='text' class='text' autocomplete='off'
          value='<?= $this->viewer->profile ?>' tabindex='3' />
   </div>
  </div>
  <br class='clear' />
</form>

<!-- pre style='padding:1em; font-size:0.9em;'>
 <?= $this->viewer->debugDump() ?>
</pre -->
