<?php
/** @file
 *
 *  View script for SearchController::index to render bookmarks results in the
 *  main content section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *
 *      referer         The URL of the referring page
 *                      (used primarily for 'Search this view');
 *      context         The chosen search context;
 *      terms           The provided search terms / query;
 *      results         The search results:
 *                          bookmarks
 *                          tags
 *                          people
 *                          items
 *
 *      main            An array of settings for the main body:
 *          displayStyle    Indicates the current presentation style -- if this
 *                          is an array, the style is 'custom';
 *          perPage         The number of results on a single page;
 *          page            The desired page of results;
 *          sortBy          Indicates the sort field used to retrieve the
 *                          current bookmark set;
 *          sortOrder       Indicates the sort order used to retrieve the
 *                          current bookmark set;
 */
Connexions::log('script/search/main-bookmarks.phtml');

$this->headLink()->appendStylesheet($this->baseUrl('/css/bookmarks.css'));

$bookmarks     = $this->results['bookmarks'];
$htmlBookmarks = $this->htmlBookmarks($this->main);
$hiddenVars    = array('referer'    => $this->referer,
                       'context'    => $this->context,
                       'terms'      => $this->terms );

//$htmlBookmarks->bookmarks = $bookmarks;
$htmlBookmarks->__set($htmlBookmarks->listName, $bookmarks);

$htmlBookmarks->setHiddenVars($hiddenVars);

$scopePath     = array('Bookmarks' => $this->baseUrl('/bookmarks'));
$htmlItemScope = $this->htmlItemScope( array(
                    'namespace' => $this->main->namespace,
                    'items'     => $htmlBookmarks->paginator,
                    'hideInput' => true,
                    'path'      => $scopePath,
                 ));

echo $htmlItemScope->render();

// Render the main view.
echo $htmlBookmarks->render();

