<?php
$this->headTitle('URL Lookup');

/*
Connexions::log("this[ %s ]",
                Connexions::varExport($this));
// */


$jQuery = $this->jQuery();
$jQuery->addStylesheet($this->baseUrl('css/url-choose.min.css'))
       ->addOnLoad('$("#choose form").validationForm();');
?>
<div id="choose" class='ui-validation-form ribbon-form line'><!-- { -->
 <div class='context-ribbon'>&nbsp;</div>
 <div class="legend unit"><!-- { -->
  <h1>URL Lookup</h1>
 </div><!-- legend } -->
 <div class="userInput lastUnit"><!-- { -->
  <form method='post'>
   <div class='field'>
    <label for='url'>Desired URL</label>
    <textarea class='text required' autocomplete='off'
               name='url' tabindex='1'><?= $this->url ?></textarea>
   </div>
   <div class='field buttons'>
    <button name='submit' tabindex='4'>Lookup</button>
   </div>
   <div class='status<?= (@isset($this->error) ? ' error' : '') ?>'>
    <?= (@isset($this->error) ? $this->error : '') ?>
   </div>
  </form>
 </div><!-- userInput } -->
</div><!-- ribbon-form -->
