<?php
/** @file
 *
 *  View script for UrlController::index with incoming members:
 *      viewer              The Model_User instance representing the current
 *                          viewer;
 *      item                A Model_Item instance representing the base item;
 *      tagInfo             A Connexions_Set_Info instance containing
 *                          information about the requested tags;
 *
 *      paginator           A Zend_Paginator instance established for the
 *                          presentation of the current Model_UserItemSet;
 *      tagSet              The Connexions_Set instance established for the
 *                          presentation of tags related to the current
 *                          ModeL_UserItemSet;
 */
$baseUrl = $this->baseUrl('/');

$links = $this->headLink();
$links->appendStylesheet($baseUrl .'css/urlItems.css');

// Grab the first item from the paginator
$item0 = $this->paginator->getItem(0);

//echo "<pre>Item:\n", $this->item->debugDump() ,"</pre>\n";
//echo "<pre>UseItem 0:\n", print_r($item0, true) ,"</pre>\n";

$this->headTitle('Bookmarks for "'. $item0['name'] .'"');

?>
<div class='columnHeader'>
 <div class='connexions_sprites bookmark_bg
             ui-corner-left ui-corer-tr'>&nbsp;</div>
 <div class='itemInfo'>
  <p>
   <span class='title'><?= $item0['name'] ?></span>
   <a href='<?= $this->item->url ?>'><?= $this->item->url ?></a>
   <?php
    /*
    if ( $this->tagInfo->hasValidItems())
        printf ("with tags '%s'.", $this->tagInfo->validItems);
    else
        printf ("NO tags.");
    */
   ?>
  </p>
 </div>
</div>

<?php
/******************************************************************************
 * Render the HTML for the primary view using the HtmlUserItems View Helper
 * that should have been prepared by the Controller.
 */
echo $this->htmlUrlItems($this->paginator,
                         $this->viewer,
                         $this->tagInfo);

/******************************************************************************
 * Render the HTML for the right-column using the HtmlItemCloud View Helper
 * that should have been prepared by the Controller.
 *
 */
$this->layout()->right
      = "<div class='columnHeader'>"
      .  "<div class='connexions_sprites tag_bg "
      .              "ui-corner-left ui-corer-tr'>&nbsp;</div>"
      .  "<p>Tags related to these bookmarks.</p>"
      . "</div>"
      .  $this->htmlItemCloud()->render();
?>

<div class='error'><?= (@isset($this->error) ? $this->error : '') ?></div>
