<?php
/** @file
 *
 *  View script for UrlController::index with incoming members:
 *      viewer      The Model_User instance representing the current viewer;
 *
 *      error       On error, an error string is provided.
 */
$baseUrl = $this->baseUrl('/');

$links = $this->headLink();
$links->appendStylesheet($baseUrl .'css/urlItems.css');

$this->headTitle('Lookup a URL');

$actionUrl = $this->url(array('url'));

$jQuery = $this->jQuery();

$jQuery->addJavascriptFile($baseUrl .'js/ui.input.js')
       ->addOnLoad("init_urlChooser();")
       ->javascriptCaptureStart();  // jQuery {
?>

/************************************************
 * Initialize the url chooser form
 *
 */
function init_urlChooser()
{
    var $form   = $('#urlChooser');
    var $url    = $form.find('input[name=url]');

    $url.input({
        emptyText:  $url.val(),
        validation: function(val) {
            return true;
        }
    });
}

<?php
$jQuery->javascriptCaptureEnd();    // jQuery }


?>
<div class='columnHeader'>
 <div class='connexions_sprites bookmark_bg
             ui-corner-left ui-corer-tr'>&nbsp;</div>
 <div class='itemInfo'>
  <p>
   <span class='title'>Lookup a URL</span>
   <span class='subTitle'>See all bookmarks for any URL.</span>
  </p>
 </div>
</div>

<form id='urlChooser' class='ui-corner-all' 
  action='<?= $this->url(array('url')) ?>'>
 <label   for='url'>URL</label>
 <input  name='url'    type='text' value='Type a URL' />
 <button name='submit' type='submit'>
  <span>lookup</span>
 </button>
 <br class='clear' />
</form>

<?php
/******************************************************************************
 * Render the HTML for the right-column using the HtmlItemCloud View Helper
 * that should have been prepared by the Controller.
 *
 */
$this->layout()->right = "Right Column...";

?>

<div class='error'><?= (@isset($this->error) ? $this->error : '') ?></div>
