<?php
/** @file
 *
 *  Feed Explorer
 */
$this->headLink()->appendStylesheet($this->baseUrl('/css/api.min.css'));

?>
<div class='columnHeader'>
 <div class='context-bg connexions_sprites settings_bg 
             ui-corner-left ui-corner-tr'>&nbsp;</div>
 <p>Feeds Explorer</p>
</div>
<div class='pane'>
 <p>There are currently three types of feeds.</p>
 <ul class='numbered'>
  <li><a href='json/'>json</a></li>
  <li><a href='rss/'>RSS</a></li>
  <li><a href='atom/'>ATOM</a></li>
 </ul>
</div>
