<?php
/** @file
 *
 *  View script for IndexController::index to render an Atom version of the
 *  main content.
 *
 *  The Connexions_View_Helper_FeedUserItems helper MUST be initialized
 *  before this view is rendered.
 *
 *  Incoming members:
 *      owner               The owner of the current item set -- either a
 *                          string or a Model_User instance;
 *      paginator           The Zend_Paginator representing the items to be
 *                          presented.
 */
Connexions_Profile::checkpoint('Connexions',
                               'IndexView Atom rendering beginning');

if ($this->owner !== '*')
    $this->headTitle($this->owner ."'s Bookmarks");
else
    $this->headTitle('Bookmarks');

$this->feedUserItems($this->paginator, 'Atom');
