<?php
/** @file
 *
 *  View script for IndexController::index to render an RSS version of the
 *  main content.
 *
 *  Incoming members:
 *      paginator           The Zend_Paginator representing the items to be
 *                          presented.
 *
 *  Sets 'feed' in the view for Bootstrap::feed_post to use in final rendering.
 */
Connexions_Profile::checkpoint('Connexions',
                               'IndexView RSS rendering beginning');

// Use the application/views/helpers/FeedBookmarks.php view helper...
$this->feed = $this->feedBookmarks($this->paginator, 'Rss');

Connexions_Profile::checkpoint('Connexions',
                               'IndexView RSS rendering COMPLETE, '
                               . 'feed is class '. get_class($this->feed));
