<?php
/** @file
 *
 *  View script for IndexController::index to render the sidebar content.
 *
 *  The Connexions_View_Helper_HtmlItemCloud helper MUST be initialized
 *  before this view is rendered.
 */

$jQuery = $this->jQuery();

$jQuery->addOnLoad("init_sidebar();")
       ->javascriptCaptureStart();
    ?>

/************************************************
 * Initialize the sidebar tab control
 *
 */
function init_sidebar()
{
    $('#sidebar-tabs').tabs();
}
    <?php
$jQuery->javascriptCaptureEnd()

?>
<div id='sidebar-tabs'>
 <ul>
  <li><a href='#sidebar-tags'  >Tags</a></li>
  <!-- li><a href='#sidebar-people'>People</a></li -->
 </ul>
 <div id='sidebar-tags'>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites tag_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>Tags related to these bookmarks.</p>
  </div>
  <?= $this->htmlItemCloud()->render() ?>
 </div>

 <!-- div id='sidebar-people'>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites user_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>People that I have tagged items for...</p>
  </div>
 </div -->
</div>
