<?php
/** @file
 *
 *  View script for IndexController::index to render the people portion of the
 *  sidebar.
 *
 *  The Connexions_View_Helper_HtmlItemCloud helper MUST be initialized
 *  before this view is rendered.
 *
 *  Incoming members:
 *      sidebarHelper   A View_Helper_HtmlSidebar instance configured with
 *                      information about the 'people' sidebar pane;
 *
 *      url             The full url for the main controller of this page;
 *      owner           The owner of the current item set -- either a string or
 *                      a Model_User instance;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      tags            A Model_Set_Tag instance containing information about
 *                      any requested tags (i.e. tag restrictions);
 */

if ($this->owner === '*')
{
?>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites user_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>People related to these bookmarks.</p>
  </div>
  <?php
}

if ($this->owner !== '*')
{
    /* Present information about the single user.
     *
     * In order for 'sidebar-user.phtml' to render properly,
     * 'css/bookmark-users.css' MUST be included.
     *
     * NOTE: Since this view scripts is most often included asynchronously,
     *       this headLink() will NOT effect the containing page.  See
     *       application/views/scripts/index/sidebar.phtml where it is
     *       currently included effectively.
    $this->headLink()
            ->appendStylesheet( $this->baseUrl('/css/bookmark-users.css'));
     */

    echo $this->partial('sidebar-user.phtml',
                        array(
                            'user'   => $this->owner,
                            'viewer' => $this->viewer,
                        ));
}
else
{
    // Tag-related users
    $config        = $this->sidebarHelper->getPane('people');
    $htmlItemCloud = $this->htmlItemCloud($config);

    echo $htmlItemCloud->render();
}
