connexions.css: main.sass
	sass -t compact main.sass connexions.css

main.sass: content.sass		\
	   grids.sass		\
	   libraries.sass	\
	   pagination.sass	\
	   sprites.sass		\
	   tabs.sass		\
	   tagCloud.sass	\
	   template.sass	\
	   ui-form.sass		\
	  themes/default/jquery-ui.css
