<?php

if ($this->owner !==  '*')
    $this->headTitle($this->owner ."'s Tags");
else
    $this->headTitle("Tags");

?>
<p>Present the Tags for <?= $this->owner ?>
                    to  <?= $this->viewer ?>
<?php   if (@empty($this->tags))
            printf (", NO tags.");
        else
            printf (" with tags '%s'", $this->tags);
?>
</p>

<div class='error'><?= (@isset($this->error) ? $this->error : '') ?></div>
