<?php
/** @file
 *
 *  View script for TagsController::index to render the tags portion of the
 *  sidebar (i.e. the 'Tags' tab).
 *
 *  Incoming members:
 *      url             The full url for the main controller of this page;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      users           A Model_Set_User instance containing information about
 *                      any requested users (i.e. tag owners);
 *      items           The items being presented in the main view;
 *
 *      main            An array of settings for the main content panel:
 *      sidebar         An array of settings for the sidebar:
 */

?>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites tag_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>Summary of <?php

    $nUsers = count($this->users);
    if ( ($nUsers === 1) && ($this->viewer->isSame($this->users[0])) )
    {
        echo "your tags.";
    }
    else if ( $nUsers > 0)
    {
        printf ("tags used by<span class='restrictions'>%s %d %s.</span>",
                ($nUsers === 1 ? 'this'   : 'these'),
                $nUsers,
                ($nUsers === 1 ? 'person' : 'people'));
    }
    else
    {
        echo "all tags.";
    }

    ?></p>
  </div>
  <?php

    $config        = $this->sidebarHelper->getPane('tags');
    $htmlItemCloud = $this->htmlItemCloud($config);

    echo $htmlItemCloud->render();
