<?php
/** @file
 *
 *  View script for TagsController::index to render the items portion of the
 *  sidebar (i.e. the 'Items' tab).
 *
 *  Incoming members:
 *      sidebarHelper   A View_Helper_HtmlSidebar instance configured with
 *                      information about the 'items' sidebar pane;
 *
 *      url             The full url for the main controller of this page;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      users           A Model_Set_User instance containing information about
 *                      any requested users (i.eusers tag restrictions);
 */

?>
  <div class='columnHeader'>
   <div class='context-bg connexions_sprites item_bg ui-corner-left'>
    &nbsp;
   </div>
   <p>Items related to these tags<?php

    $nUsers = count($this->users);
    if ($nUsers > 0)
    {
        printf ("<span class='restrictions'>and %d %s.</span>",
                $nUsers,
                ($nUsers === 1 ? 'person' : 'people'));
    }
    else
    {
        echo ".";
    }

    ?></p>
  </div>
  <?php

    $config        = $this->sidebarHelper->getPane('items');
    $htmlItemCloud = $this->htmlItemCloud($config);

    echo $htmlItemCloud->render();
