#!/usr/bin/env php
<?php
define('CLI_DIR', realpath(dirname(__FILE__)));

require_once(CLI_DIR. '/bootstrap.php');

ini_set('display_startup_errors', 1);
ini_set('display_errors',         1);
error_reporting(E_ALL);

$prog = array_shift($argv);
foreach ($argv as $arg)
{
    printf ("Instantiate: '%s'...", $arg);
    $inst = new $arg();
    echo " done\n";
}
