<?php
/** @file
 *
 *  If search results are available, present them, otherwise, present a search
 *  form.
 *
 */

// Disable the 'same' / 'Search this view' context
$this->navMenu(false)->disableSearchContext('same');

if (! isset($this->results))
{
    // Render a search form
    echo $this->render('search/form.phtml');
    return;
}

/********************************************************************
 * Render results
 *
 */
$this->headTitle("Search results for '". $this->terms ."'");

$nResults = count($this->results);
if ($nResults < 1)
{
    printf ("<p>No results found for '%s'.</p>", $this->terms);
}
else
{
    foreach ($this->results as $section => $items)
    {
        printf ("<p>%s %s results matching '%s'.</p>",
                number_format(count($items)),
                preg_replace('/s$/', '', $section),
                $this->terms);

        echo "<ul class='results'>";
        /*
        printf ("<li><pre>%s</pre></li>\n",
                htmlspecialchars($items->debugDump()));
        */
        echo "</ul>";
    }
}

?>

<div class='error'><?= (@isset($this->error) ? $this->error : '') ?></div>
