<?php
if (! @is_array($this->postInfo))
    $this->postInfo = array();

//$noConflict = Zend_JQuery_View_Helper_JQuery::getJQueryHandler();

$jQuery = $this->jQuery();
$jQuery->addStylesheet($this->baseUrl('css/post.css'))
       //->addStylesheet($this->baseUrl('css/validationForm.css'))
       ->addOnLoad('$("#post form").bookmarkPost({statusEl: ".status"});');

if (isset($this->postInfo['itemId']) && ($this->postInfo['mode'] !== 'post'))
{
    $verb = 'Update';
    $adj  = '';
}
else
{
    $verb = 'Post';
    $adj  = 'new';
}

?>
<div class="line"><!-- { -->
 <div id="post" class='ui-validation-form ribbon-form'>
  <div class='context-ribbon'>&nbsp;</div>
  <div class="legend unit"><!-- { -->
   <div class='context-bg connexions_sprites bookmark_bg'>
     &nbsp;
   </div>
   <h1><?= $verb ?></h1>
   <p>a <?= $adj ?> bookmark</p>
   <div class='status<?= (@isset($this->error) ? ' error' : '') ?>'>
    <?= (@isset($this->error) ? $this->error : '') ?>
   </div>
  </div><!-- legend } -->
  <div class="userInput unit"><!-- { -->
    <?= $this->render('post/index-partial.phtml') ?>
  </div><!-- userInput } -->
  <br class='clear' />
 </div>
</div><!-- line } -->
