<?php
if (! @is_array($this->postInfo))
    $this->postInfo = array();

//$noConflict = Zend_JQuery_View_Helper_JQuery::getJQueryHandler();

/*
$jQuery = $this->jQuery();
$jQuery->addOnLoad('$("#post form").bookmarkPost({$status: ".status"});');
// */

if (isset($this->postInfo['itemId']) && ($this->postInfo['mode'] !== 'post'))
{
    $verb = 'Update';
    $adj  = '';
}
else
{
    $verb = 'Post';
    $adj  = 'new';
}

$id = 'post';
?>
<div class="line"><!-- { -->
 <div id="<?= $id ?>" class='ui-validation-form ribbon-form'>
  <div class='context-ribbon'>&nbsp;</div>
  <div class="legend unit"><!-- { -->
   <div class='context-bg connexions_sprites bookmark_bg'>
     &nbsp;
   </div>
   <h1><?= $verb ?></h1>
   <p>a <?= $adj ?> bookmark</p>
   <div class='status<?= (@isset($this->error) ? ' error' : '') ?>'>
    <?= (@isset($this->error) ? $this->error : '') ?>
   </div>
  </div><!-- legend } -->
  <div class="userInput unit"><!-- { -->
    <?= $this->render('post/main.phtml') ?>
  </div><!-- userInput } -->
  <br class='clear' />
 </div>
</div><!-- line } -->
<script type='text/javascript'>
/* Include an event delegate to adjust our legend if the bookmarkPost widget
 * changes the 'isEdit' state.
 */
(function($) {
    var $post   = $('#<?= $id ?>');
    $post.delegate('form', 'isEditChanged', function(e, newValue) {
        var title       = 'Post';
        var subTitle    = 'a new bookmark';
        if (newValue)
        {
            title       = 'Update';
            subTitle    = 'a bookmark';
        }

        var $legend = $post.find('.legend:first');
        $legend.find('h1:first').text(title);
        $legend.find('p:first').text(subTitle);
    });
 }(jQuery));
</script>
