<?php
if (! @is_array($this->postInfo))
    $this->postInfo = array();
//$this->postInfo['url'] = 'url://to-edit/';

//$noConflict = Zend_JQuery_View_Helper_JQuery::getJQueryHandler();

$jQuery = $this->jQuery();
$jQuery->addStylesheet($this->baseUrl('css/post.css'))
       ->addStylesheet($this->baseUrl('css/validationForm.css'))
       ->addOnLoad('$("#post form").bookmarkPost({statusEl: ".status"});');

?>
<div class="line"><!-- { -->
 <div id="post" class='ui-validation-form'>
  <div class='context-ribbon'>&nbsp;</div>
  <div class="legend unit"><!-- { -->
   <div class='context-bg connexions_sprites bookmark_bg'>
     &nbsp;
   </div>
   <h1>Post</h1>
   <p>a new bookmark</p>
   <div class='status<?= (@isset($this->error) ? ' error' : '') ?>'>
    <?= (@isset($this->error) ? $this->error : '') ?>
   </div>
  </div><!-- legend } -->
  <div class="userInput unit"><!-- { -->
    <?= $this->render('post/index-partial.phtml') ?>
  </div><!-- userInput } -->
  <br class='clear' />
 </div>
</div><!-- line } -->
