<?php
/** @file
 *
 *  Bookmark Post form partial.
 *
 *  Incoming data:
 *      postInfo        POST form initialization data, if any.
 *                          [ userId ]
 *                          [ itemId ]
 *                          url
 *                          name
 *                          description
 *                          rating
 *                          isFavorite
 *                          isPrivate
 *                          tags
 *                          mode        'post' | null ('edit')
 *
 *      suggest         If suggestions should be included, this is an array of
 *                      configuration for suggestions comprised of:
 *          tags
 *              recommended An array of configuration data for
 *                          View_Helper_HtmlItemCloud for the 'recommended'
 *                          section within the 'tags' tab of 'suggestions';
 *              top         An array of configuration data for
 *                          View_Helper_HtmlItemCloud for the 'top'
 *                          section within the 'tags' tab of 'suggestions';
 *          people
 *              network     An array of configuration data for
 *                          View_Helper_HtmlItemCloud for the 'network'
 *                          section within the 'people' tab of 'suggestions';
 *
 *  This requires connexions.bookmarkPost.js as well as jQuery activation via:
 *      $this->jQuery()->addOnLoad('$("... form").bookmarkPost();');
 *
 */
if (! @is_array($this->postInfo))
    $this->postInfo = array();

$id = 'bookmarkPost';
?>
   <form id='<?= $id ?>' method='post'><!-- { -->
    <?php if (isset($this->postInfo['userId'])): ?>
    <input name='userId' type='hidden'
          value='<?= $this->postInfo['userId'] ?>' />
    <?php endif ?>
    <?php if (isset($this->postInfo['itemId'])): ?>
    <input name='itemId' type='hidden'
          value='<?= $this->postInfo['itemId'] ?>' />
    <?php endif ?>
    <div class='unit item-status'><!-- { -->
     <div class='field favorite'>
      <label for='isFavorite'>Favorite</label>
      <input name='isFavorite'
            type='checkbox' value='true'
            <?= ($this->postInfo['isFavorite'] ? ' checked' : '') ?> />
     </div>

     <div class='field private'>
      <label for='isPrivate'>Private</label>
      <input name='isPrivate'
            type='checkbox' value='true'
            <?= ($this->postInfo['isPrivate'] ? ' checked' : '') ?> />
     </div>
    </div><!-- item-status } -->

    <div class='unit item-data'><!-- { -->
     <div class='field userRating'>
      <label for='rating'>rating</label>
      <?= $this->htmlStarRating($this->postInfo['rating'],
                                'stars-wrapper') ?>
      <!-- div class='stars-wrapper'>
       <input name='rating' type='radio' value='1' title='Terrible'
             <?= ($this->postInfo['rating'] == '1'
                     ? " checked='true'" : '') ?> />
       <input name='rating' type='radio' value='2' title='Fair'
             <?= ($this->postInfo['rating'] == '2'
                     ? " checked='true'" : '') ?> />
       <input name='rating' type='radio' value='3' title='Average'
             <?= ($this->postInfo['rating'] == '3'
                     ? " checked='true'" : '') ?> />
       <input name='rating' type='radio' value='4' title='Good'
             <?= ($this->postInfo['rating'] == '4'
                     ? " checked='true'" : '') ?> />
       <input name='rating' type='radio' value='5' title='Excellent'
             <?= ($this->postInfo['rating'] == '5'
                     ? " checked='true'" : '') ?> />
      </div -->
     </div>

     <div class='field item-name'>
      <label for='name'>Bookmark name / title</label>
      <input type='text' class='text required' autocomplete='off'
             name='name' value='<?= $this->postInfo['name'] ?>'
                      tabindex='1' />
     </div>
     <div class='field item-url<?= (! @empty($this->postInfo['url'])
                                         ? ' click-to-edit'
                                         : '') ?>'>
      <label for='url'>URL to bookmark</label>
      <input type='text' class='text required' autocomplete='off'
             name='url'  value='<?= $this->postInfo['url'] ?>'
                      tabindex='2' />
     </div>
     <div class='field item-description'>
      <label for='description'>Description / Notes for this bookmark</label>
      <textarea class='text'
                 name='description'
             tabindex='3'><?= $this->postInfo['description'] ?></textarea>
     </div>
     <div class='field item-tags'>
      <label for='tags'>Tags</label>
      <textarea class='text required'
                 name='tags'
             tabindex='4'><?= $this->postInfo['tags'] ?></textarea>
     </div>
     <br class='clear' />
    </div><!-- item-data } -->

    <div class='buttons'>
     <button name='cancel' tabindex='5'>Cancel</button>
     <button name='submit' tabindex='6'>Save</button>
     <br class='clear' />
    </div>

<? if (is_array($this->suggest)): ?>
    <div class='suggestions'>

      <ul><?php

        foreach ($this->suggest as $tab => $tabConfig)
        {
            if (! is_array($tabConfig))
            {
                continue;
            }

            $title = (isset($tabConfig['title'])
                        ? $tabConfig['title']
                        : ucfirst($tab));

            ?>

        <li><a href='#suggestions-<?= $tab ?>'><span><?= $title ?></span></a></li><?php
        }

        ?>

      </ul>

      <?php
        foreach ($this->suggest as $tab => $tabConfig)
        {
            if (! is_array($tabConfig))
            {
                continue;
            }

            ?>

      <ul id='suggestions-<?= $tab ?>'><?php

            foreach ($tabConfig as $section => $sectionConfig)
            {
                if (! is_array($sectionConfig))
                {
                    continue;
                }

                $title = (! empty($sectionConfig['title'])
                            ? $sectionConfig['title']
                            : ucfirst($section));
                $css   = ( (! isset($sectionConfig['expanded']) ||
                            ($sectionConfig['expanded'] === true))
                            ? 'expanded'
                            : 'collapsed');

                ?>

        <li class='collapsable <?= $section ?>'>
          <h3 class='toggle <?= $css ?>'><span><?= $title ?></span></h3>
          <div class='content'><?php

                /* Handle any sub-sections that can be rendered independently
                 * (e.g. 'tags-recommended')
                 */
                if (! empty($sectionConfig['items']))
                {
                    if (($tab === 'tags') && ($section === 'recommended'))
                    {
                        echo $this->render('post/main-tags-recommended.phtml');
                    }
                    else
                    {
                        echo $this->htmlItemCloud($sectionConfig)->render();
                    }
                }
                else
                {
                    echo '&nbsp;';
                }

                ?>

          </div>
        </li>
                <?php
        }

            ?>

      </ul><?php
        }

        ?>

    </div>
<? endif ?>

   </form><!-- form } -->
<?php

/* Establish configuration for and schedule instantiation of a new
 * Javascript connexions.bookmarkPost() instance targeting the form rendered
 * just above.
 */
$postConfig = array(
    'isEdit'        => ($this->postInfo['mode'] === 'post'
                            ? false
                            : true),
);
$postConfig = array_merge($postConfig, $this->postInfo);

$postConfig = Zend_Json::encode($postConfig);

$jsWait = false;
$jsLoad = "$('#{$id}').bookmarkPost({$postConfig});";
if ($jsWait === false)
{
    // Instantiate the Javascript widget immediately
    ?>
<script type='text/javascript'>
(function($) {
    <?= $jsLoad ?>
 }(jQuery));
</script>
    <?php
}
else
{
    // Wait until DOM-ready to instantiate the Javascript widget
    $this->jQuery()->addOnLoad( $jsLoad );
}
