<?php
/** @file
 *
 *  Render the recommended tags for the suggestions area of a Bookmark Post
 *  form.
 *
 *  Incoming data:
 *      tabs                        An array of 'tabs' configuration;
 *          tags                    Configuration for the 'tags' tab;
 *              sections            An array of sections within this tab;
 *                  top             Configuration for the 'tags/top' section;
 *                      config      Helper configuration;
 */
$tab     =& $this->tabs['tags'];
$section =& $tab['sections']['top'];
$config  =& $section['config'];

if ($config['items'] !== null)
{
    echo $this->htmlItemCloud($config)->render();
}
else
{
    echo '<p class="ui-state-highlight">Empty</p>';
}
