<?php
/** @file
 *
 *  View script for InboxController::index to render the sidebar content.
 *
 *  The Connexions_View_Helper_HtmlItemCloud helper MUST be initialized
 *  before this view is rendered.
 *
 *  Incoming members:
 *      senderSet           The Connexions_Set instance established for the
 *                          presentation of users who have tagged items for
 *                          this user (i.e. all users related to the current
 *                                          ModeL_UserItemSet);
 */

$jQuery = $this->jQuery();

$jQuery->addOnLoad("init_sidebar();")
       ->javascriptCaptureStart();
    ?>

/************************************************
 * Initialize the sidebar tab control
 *
 */
function init_sidebar()
{
    $('#sidebar-tabs').tabs();
}
    <?php
$jQuery->javascriptCaptureEnd();



$showAvatar = true;
if ( isset($this->htmlUserItems))
{
    $itemMeta   = $this->htmlUserItems()->getShowMeta();
    $showAvatar = $itemMeta['item:data:userId:avatar'];
}

$nSenders   = count($this->senderSet);


?>

<div id='sidebar-tabs'><!-- { -->
 <ul>
  <li><a href='#sidebar-tags'  >Tags</a></li>
  <li><a href='#sidebar-people'>People</a></li>
 </ul>
 <div id='sidebar-tags'>
  <div class='columnHeader'>
   <div class='connexions_sprites tag_bg ui-corner-left ui-corer-tr'>
    &nbsp;
   </div>
   <p>Tags related to these bookmarks.</p>
  </div>
  <?= $this->htmlItemCloud()->render() ?>
 </div>
 <div id='sidebar-people'><!-- { -->
  <div class='columnHeader'>
   <div class='connexions_sprites user_bg ui-corner-left ui-corer-tr'>
    &nbsp;
   </div>
   <?= sprintf("<p>%d sender%s of these bookmarks.</p>",
               $nSenders, ($nSenders == 1 ? "" : "s")) ?>
  </div>
  <div id='sendersList'><!-- { -->
   <!-- div class='listRelation connexions_sprites relation_ltr'>
    &nbsp;
   </div -->
   <ul class='users'><!-- { -->
     <?php

$idex = 0;
foreach ($this->senderSet as $sender)
{
    $css = 'user';
    if ($idex++ >= ($nSenders - 1))
        $css .= ' last';

    $senderUrl = $this->url(array('controller' => 'index',
                                  'action'     => 'index',
                                  'owner'      => $sender->name));

    $avatarHtml = '';
    if ($showAvatar === true)
    {
        $avatarHtml .= "<div class='avatar img icon-highlight'>"
                    .   "<a href='{$senderUrl}' title='{$sender->fullName}'>";

        if ( ! @empty($sender->pictureUrl))
        {
            // Include the user's picture / avatar
            $avatarHtml .= "<img src='{$sender->pictureUrl}' />";
        }
        else
        {
            // Include the default user icon
            $avatarHtml .= "<div class='ui-icon ui-icon-person'>"
                        .   "&nbsp;"
                        .  "</div>";
        }

        $avatarHtml .=  "</a>"
                    .  "</div>";
    }

    $userIdHtml = '';
    //if ($showMeta['user:data:userId'] === true)
    {
        $userIdHtml .= "<div class='userId'>"
                    .   "<a href='{$senderUrl}' title='{$sender->fullName}'>"
                    .    "<span class='name'>{$sender->name}</span>"
                    .   "</a>"
                    .  "</div>";
    }

    //echo $this->htmlUsersUser($sender, $this->viewer, $showMeta);
    ?>
    <li class='<?= $css ?>'>
     <div class='stats'>
      <a class='countItems' title='<?= $sender->fullName ?>'
          href='<?= $senderUrl ?>'>
       <?= $sender->getWeight() ?>
      </a>
     </div>
     <div class='data'>
      <?= $avatarHtml ?>
      <?= $userIdHtml ?>
      <br class='clear' />
     </div>
    </li>

    <?php
}

?>
   </ul><!-- } -->
  </div><!-- senderList } -->
 </div><!-- sidebar-people } -->
</div><!-- sidebar-tabs } -->
