<?php
/** @file
 *
 *  View script for InboxController::index to render the sidebar content.
 *
 *  Incoming members:
 *      sidebarHelper   A View_Helper_HtmlSidebar instance configured with
 *                      (at least general) information about the sidebar;
 *
 *      url             The full url for the main controller of this page;
 *      owner           The owner of the current item set -- either a string or
 *                      a Model_User instance;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *      tags            A Model_Set_Tag instance containing information about
 *                      any requested tags AND the 'for:%user%' for this inbox;
 *
 */

/* Invoke the Html Sidebar View helper to render the sidebar based upon
 * settings in $this->sidebar established by InboxController::_prepareSidebar
 *
 * This will either render the sidebar partials immediately or setup
 * asynchronous loading, depending on $this->sidebar['async']
 */
echo $this->sidebarHelper->render('inbox/');
