<ul>
 <li class='collapsable'>
  <h3 class='toggle collapsed faq-question'><span>Question 1</span></h3>
  <div class='faq-answer'>
   <p>Answer 1</p>
  </div>
 </li>
 <li class='collapsable'>
  <h3 class='toggle collapsed faq-question'><span>Question 2</span></h3>
  <div class='faq-answer'>
   <p>Answer 2</p>
  </div>
 </li>
 <li class='collapsable'>
  <h3 class='toggle collapsed faq-question'><span>Question 3</span></h3>
  <div class='faq-answer'>
   <p>Answer 3</p>
  </div>
 </li>
</ul>
