<ul>
 <li class='collapsable'>
  <h3 class='toggle collapsed faq-question'><span>What is connexions?</span></h3>
  <div class='faq-answer'>
   <p>Connexions is a collaborative, social bookmarking/folksonomy system.  It is similar to del.icio.us, simply, furl, and BlinkList.  Connexions provides an attractive, easy to use interface that allows individuals to tag anything that has a unique identifier (e.g. a URL, URI) with one or more keywords.  Tagged items can then be located based upon tags and/or the individuals that tagged them.  The system also permits users to rate the quality of items, mark items as shared or private, and indicate which items are favorites.</p>
  </div>
 </li>
 <li class='collapsable'>
  <h3 class='toggle collapsed faq-question'><span>Question 2</span></h3>
  <div class='faq-answer'>
   <p>Answer 2</p>
  </div>
 </li>
 <li class='collapsable'>
  <h3 class='toggle collapsed faq-question'><span>Question 3</span></h3>
  <div class='faq-answer'>
   <p>Answer 3</p>
  </div>
 </li>
</ul>
