<?php
/** @file
 *
 *  View script for SearchController::index to render bookmarks results in the
 *  main content section.
 *
 *  Incoming members:
 *      baseUrl         The base url for the main controller of this page
 *                      without any differentiating parameters
 *                      (e.g. tag restrictions);
 *      url             The full url for the main controller of this page
 *                      with differentiating parameters;
 *      viewer          The Model_User instance representing the current
 *                      viewer;
 *
 *      referer         The URL of the referring page
 *                      (used primarily for 'Search this view');
 *      context         The chosen search context;
 *      terms           The provided search terms / query;
 *
 *      results                 An array of section information:
 *          bookmarks           An array of settings for the bookmarks section:
 *              where           Additional retrieval conditions;
 *              displayStyle    Indicates the current presentation style --
 *                              if this is an array, the style is 'custom';
 *              perPage         The number of results on a single page;
 *              page            The desired page of results;
 *              sortBy          Indicates the sort field used to retrieve the
 *                              current bookmark set;
 *              sortOrder       Indicates the sort order used to retrieve the
 *                              current bookmark set;
 */
Connexions::log('script/search/main-bookmarks.phtml');
$sectionConfig = $this->results['bookmarks'];

$htmlBookmarks = $this->htmlBookmarks($sectionConfig);

$count = $htmlBookmarks->bookmarks->getTotalCount();
$htmlBookmarks->html = array(
    'prepend'   => sprintf ( "<div class='searchStats'>"
                            . "<span class='count'>%s</span> "
                            . "%s"
                            ."</div>\n",
                            number_format($count),
                            ($count === 1 ? 'bookmark' : 'bookmarks')),
    'append'    => "<br class='clear' />",
);

// Render the bookmarks section.
echo $htmlBookmarks->render();
