<?php

$baseUrl = $this->baseUrl();
$config  = Connexions::getConfig();
$app     = $config->app;
$contact = $config->contact;

?>
  <div id="pageFooter" class="foot" role="banner">
   <ul class='footer-nav'>
    <li class='icon'
            ><img src='<?= $this->baseUrl('/images/logo.png') ?>'
                  title='connexions' /></li>
    <li class='internal'
            ><a href='<?= $this->baseUrl('/help/about') ?>'>About</a></li>
    <li class='sep'>&middot;</li>
    <li class='internal'
            ><a href='<?= $this->baseUrl('/help') ?>'>Help</a></li>
    <li class='sep'>&middot;</li>
    <li class='internal'
            ><a href='<?= $this->baseUrl('/help/developers') ?>'>API</a></li>
    <li class='sep'>&middot;</li>
    <?php
    if ($contact->services)
    {
        $nServices = count($contact->services);
        $idex      = 0;
        foreach ($contact->services as $type => $service)
        {
            ?>
    <li class='external'
            ><a href='<?= $service->url ?>'><?= ucfirst($type) ?></a></li>
            <?php

            if (++$idex < $nServices)
            {
                ?>
    <li class='sep'>&middot;</li>
                <?php
            }
        }
    }

    ?>
    <li class='org'><?php

    if ($contact->org)
    {
        $img = ($contact->org->img
                    ? "<img src='{$contact->org->img}' />"
                    : "");

        ?><a href='<?= $contact->org->url ?>'
               ><?= $img ?><span class='name'
               ><?= $contact->org->name ?></span></a>
        <?php
    }

    if ($app && $app->version && $app->version->major)
    {
        ?><div class='version'>
            <span class='major'><?= $app->version->major ?>.</span
           ><span class='minor'><?= $app->version->minor ?></span>
            <span class='build'>(build <?= $app->version->build ?>)</span>
          </div><?php
    }

    ?>
    </li>
   </ul>

   <?= $this->HtmlDbProfile() ?>
  </div>
 </div><!-- page } -->
<?= $this->render('base-footer.phtml') ?>
