<?php
//Connexions_Profile::checkpoint('Connexions', 'layout::BEGIN');

echo $this->render('header.phtml');
?>

  <div id="pageContent" class="body"><!-- { body -->
   <div class="rightCol" role="complementary"><!-- { right -->
    <?= $this->placeholder('right') ?>
   </div><!-- right } -->
   <div class="main" role="main"><!-- { main -->
    <?= $this->layout()->content ?>
   </div><!-- main } -->
  </div><!-- body } -->
  <div id="notifications">
    <!-- Default notification template -->
    <div id="default">
      <a class="ui-notify-close ui-notify-cross" href="#">x</a>
      <h1>#{title}</h1>
      <p>#{text}</p>
    </div>
  </div>

<?php
echo $this->render('footer.phtml');

Connexions_Profile::stop('Connexions', 'layout::COMPLETE');
