<?php
$request = Connexions::getRequest();

// /*
echo "<pre>Request Params:\n";
print_r($request->getParams());
echo "</pre>\n";
// */

$searchTerm     = $request->getParam('q', null);
$searchContext  = $request->getParam('searchContext', 'all');
$searchContexts = Zend_Registry::get('config')->searchContext;
if ($searchContexts instanceof Zend_Config)
{
    $searchContexts = $searchContexts->toArray();
}
else
{
    $searchContexts = array();
}

echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>connexions</title>
  <?= $this->headLink()->appendStylesheet(Connexions::url('/css/main.css')) ?>

  <script type='text/javascript'>
    function activateToggles()
    {
        /* General document click listener to close any open item on an
         * unhandled click.
         */
        $(document).click(function() {
                $('.open').removeClass('open');
            });

        /* Activate all toggles in our page header
         *  (e.g. navigation menus, search choices).
         */
        //$('#pageHeader .tabs .toggle,#search .choices label')
        $('#pageHeader .toggle').click(
            function(event) {
                event.preventDefault();
                event.stopPropagation();

                var $el     = $(this).parent();
                var isOpen  = $el.hasClass('open');

                // Close any toerh currently opened sub-menus
                $('.open').removeClass('open');

                // Toggle the current item
                if (! isOpen)
                    $el.addClass('open');
            });
    }

    function activateSearch()
    {
        var $form           = $('#search');
        var $input          = $form.find('input[name=q]');
        var $context        = $form.find('input[name=searchContext]');
        var contextLabel    = '';

        // Activate our search choice selections
        $('#search .choices .list li').click(
            function(event) {
                var $li         = $(this);
                var $choices    = $li.parent().parent();


                // Grab the new choice value from the li.id
                var choice  = $li.attr('id').replace(/search-choice-/, '');
                $context.val(choice);

                // Now, set the current value in the query input box
                contextLabel = $li.text();
                $input.val(contextLabel);

                // Remove the 'on' class from all sibling lis
                $li.siblings('.on').removeClass('on');

                // And last, add the 'on' class to this li
                $li.addClass('on');
        });

        /* When the input box receives focus, if the current value is the label
         * of the current context, empty it.
         */
        $input.focus(function() {
            if ($input.val() == contextLabel)
                $input.val('');
            $input.addClass('focus');
        });

        /* When the input box looses focus, if the current value is empty,
         * set it to the current label.
         */
        $input.blur(function() {
            if ($input.val().length < 1)
                $input.val(contextLabel);
            $input.removeClass('focus');
        });
    }
  </script>
  <!-- Use the google CDN -->
  <script type='text/javascript' src='http://www.google.com/jsapi'></script>
  <script type='text/javascript'>
    google.load('jquery', '1');

    google.setOnLoadCallback(function() {
        activateToggles();
        activateSearch();
    });
  </script>

</head>

<body>
 <div class="page liquid"><!-- { page -->
  <div id="pageHeader" class="head" role="banner"><!-- { head -->
   <h1 id='siteName'>
    <a href="<?= Connexions::url('/') ?>">
     <span>conne</span>
     <img src="<?= Connexions::url('/images/logo.gif') ?>" alt="x" />
     <span>ions</span>
    </a>
   </h1>
   <div class='tabs'><!-- tabs { -->
    <?php
        /* Present the Navigation Menu */
        $nav   = $this->navigation();

        /*
        $acl  = $nav->getAcl();
        $role = $nav->getRole();
        printf("role[ %s ]<br />\n", $role);
echo "<pre>acl:\n";
print_r($acl);
echo "</pre>\n";
        */

        $items = $nav->findOneByLabel('nav_menu');

        echo $this->navigation()
                  ->menu()
                  ->renderPartial($items, 'nav_menu.phtml');

    ?>
   </div><!-- tabs } -->
 
   <div class='global'><!-- global { -->
    <?php
        /* Present the Navigation Bar */
        $nav   = $this->navigation();
        $items = $nav->findOneByLabel('nav_bar');

        echo $this->navigation()
                  ->menu()
                  ->renderMenu($items,
                               array('ulClass'  => 'nav'));

    ?>

    <form id='search' action='<?= Connexions::url('/search') ?>' method='post'>
     <div class='searchBox'><!-- searchBox { -->
      <div class='searchInput'><!-- searchInput { -->
       <div class='choices'>
        <label class='toggle' for='q'><em>search type</em></label>
        <input name='searchContext' type='hidden'
              value='<?= $searchContext ?>' />
        <ul class='list'>
         <?php
            /* Render the list of available search contexts.
             *
             * This is defined in 'application/configs/application.ini' via
             *     'searchContext.<name> = <label>
             */
            $contextText = 'Search connexions';
            foreach($searchContexts as $name => $label)
            {
                $id       = 'search-choice-'. $name;
                $cssClass = '';
             
                if ($searchContext == $name)
                {
                    $cssClass    = " class='on'";
                    $contextText = $label;
                }

                printf ("         <li id='%s'%s>%s</li>\n",
                        $id, $cssClass, $label);
            }
         ?>
        </ul>
       </div>
       <input name='q'       type='text' class='input'
             value="<?= (@empty($searchTerm) ? $contextText : $searchTerm) ?>"
              autocomplete='off' maxlength='255' size='30' />
       <script type='text/javascript'>
        // When we click on the search input box, if the text
       </script>
      </div><!-- searchInput } -->
      <input type='submit' class='submit' value='search' />
     </div><!-- searchBox } -->
    </form>
   </div><!-- global } -->
   <br class='clear' />
  </div><!-- head } -->

  <div id="pageContent" class="body"><!-- { body -->
   <div class="main" role="main"><!-- { main -->
    <?= $this->layout()->content ?>
   </div><!-- main } -->
   <div class="rightCol" role="complementary"><!-- { right -->
   </div><!-- right } -->
  </div><!-- body } -->

  <div id="pageFooter" class="foot" role="banner">
   Footer
  </div>
 </div><!-- page } -->
</body>

</html>
